module Database exposing (..)

import String


type TextSource
    = God
    | RNN


type alias Document =
    { source : TextSource
    , passage : String
    , content : String
    }


documentsEnglish : List Document
documentsEnglish =
    List.map (uncurry (Document God)) divineTextsEnglish
        ++ List.map (uncurry (Document God)) benignTextsEnglish


divineTextsEnglish : List ( String, String )
divineTextsEnglish =
    [ ( "Act 14:5", "And when they had preached the word in Perga, they went down into Attalia:" )
    , ( "Luk 18:3", "And when he heard this, he was very sorrowful: for he was very rich." )
    , ( "Job 4:6", "Is not this thy fear, thy confidence, thy hope, and the uprightness of thy ways?" )
    , ( "Act 28:4", "And some believed the things which were spoken, and some believed not." )
    , ( "Ezr 8:4", "Of the sons also of Bigvai; Uthai, and Zabbud, and with them seventy males." )
    , ( "Psa 119:3", "I will never forget thy precepts: for with them thou hast quickened me." )
    , ( "Jer 52:5", "So the city was besieged unto the eleventh year of king Zedekiah." )
    , ( "Ecc 4:9", "Two are better than one; because they have a good reward for their labour." )
    , ( "Psa 56:0", "In God will I praise his word: in the LORD will I praise his word." )
    , ( "Ch1 25:7", "The twentieth to Eliathah, he, his sons, and his brethren, were twelve:" )
    , ( "Pro 7:2", "Now is she without, now in the streets, and lieth in wait at every corner.)" )
    , ( "Psa 13:6", "I will sing unto the LORD, because he hath dealt bountifully with me." )
    , ( "Act 11:0", "And this was done three times: and all were drawn up again into heaven." )
    , ( "Pro 3:4", "Surely he scorneth the scorners: but he giveth grace unto the lowly." )
    , ( "Job 38:8", "When the dust groweth into hardness, and the clods cleave fast together?" )
    , ( "Mat 22:3", "He saith unto them, How then doth David in spirit call him Lord, saying," )
    , ( "Psa 60:5", "That thy beloved may be delivered; save with thy right hand, and hear me." )
    , ( "Heb 12:1", "And so terrible was the sight, that Moses said, I exceedingly fear and quake:)" )
    , ( "Psa 132:8", "Arise, O LORD, into thy rest; thou, and the ark of thy strength." )
    , ( "Pro 24:2", "For their calamity shall rise suddenly; and who knoweth the ruin of them both?" )
    , ( "Joh 9:6", "Then said they to him again, What did he to thee? how opened he thine eyes?" )
    , ( "Pro 13:7", "A wicked messenger falleth into mischief: but a faithful ambassador is health." )
    , ( "Job 20:3", "Though he spare it, and forsake it not; but keep it still within his mouth:" )
    , ( "Rom 15:2", "Let every one of us please his neighbour for his good to edification." )
    , ( "Mat 5:3", "Blessed are the poor in spirit: for theirs is the kingdom of heaven." )
    , ( "Pro 8:0", "I lead in the way of righteousness, in the midst of the paths of judgment:" )
    , ( "Gen 23:5", "And the children of Heth answered Abraham, saying unto him," )
    , ( "Exo 21:1", "Now these are the judgments which thou shalt set before them." )
    , ( "Mar 11:6", "And they said unto them even as Jesus had commanded: and they let them go." )
    , ( "Lam 5:4", "The elders have ceased from the gate, the young men from their musick." )
    , ( "Ti2 2:7", "Consider what I say; and the Lord give thee understanding in all things." )
    , ( "Ch1 26:4", "And Shebuel the son of Gershom, the son of Moses, was ruler of the treasures." )
    , ( "Mar 7:2", "And ye suffer him no more to do ought for his father or his mother;" )
    , ( "Pe1 1:9", "Receiving the end of your faith, even the salvation of your souls." )
    , ( "Rom 11:7", "For this is my covenant unto them, when I shall take away their sins." )
    , ( "Psa 119:6", "Great are thy tender mercies, O LORD: quicken me according to thy judgments." )
    , ( "Num 16:8", "And he stood between the dead and the living; and the plague was stayed." )
    , ( "Psa 123:1", "Unto thee lift I up mine eyes, O thou that dwellest in the heavens." )
    , ( "Job 9:8", "I am afraid of all my sorrows, I know that thou wilt not hold me innocent." )
    , ( "Luk 4:7", "And the fame of him went out into every place of the country round about." )
    , ( "Neh 7:4", "The children of Bazlith, the children of Mehida, the children of Harsha," )
    , ( "Col 3:9", " Husbands, love your wives, and be not bitter against them." )
    , ( "Gen 15:8", "And he said, LORD God, whereby shall I know that I shall inherit it?" )
    , ( "Mar 7:3", "All these evil things come from within, and defile the man." )
    , ( "Lev 16:5", "And the fat of the sin offering shall he burn upon the altar." )
    , ( "Heb 10:7", "For yet a little while, and he that shall come will come, and will not tarry." )
    , ( "Eze 7:5", "Thus saith the Lord GOD; An evil, an only evil, behold, is come." )
    , ( "Pro 18:9", "He also that is slothful in his work is brother to him that is a great waster." )
    , ( "Lev 11:1", "And the LORD spake unto Moses and to Aaron, saying unto them," )
    , ( "Job 30:7", "Among the bushes they brayed; under the nettles they were gathered together." )
    , ( "Exo 25:9", "Of a talent of pure gold shall he make it, with all these vessels." )
    , ( "Mat 14:6", "But Jesus said unto them, They need not depart; give ye them to eat." )
    , ( "Luk 2:2", "And Jesus increased in wisdom and stature, and in favour with God and man." )
    , ( "Lev 13:5", "But if the scall spread much in the skin after his cleansing;" )
    , ( "Psa 135:5", "For I know that the LORD is great, and that our Lord is above all gods." )
    , ( "Sol 7:1", "Come, my beloved, let us go forth into the field; let us lodge in the villages." )
    , ( "Pro 1:9", "For that they hated knowledge, and did not choose the fear of the LORD:" )
    , ( "Psa 51:2", "Restore unto me the joy of thy salvation; and uphold me with thy free spirit." )
    , ( "Job 22:9", "The righteous see it, and are glad: and the innocent laugh them to scorn." )
    , ( "Pro 14:9", "Fools make a mock at sin: but among the righteous there is favour." )
    , ( "Joh 10:4", "I am the good shepherd, and know my sheep, and am known of mine." )
    , ( "Psa 62:1", "Truly my soul waiteth upon God: from him cometh my salvation." )
    , ( "Gen 32:4", "Two hundred she goats, and twenty he goats, two hundred ewes, and twenty rams," )
    , ( "Ch2 9:8", "And they brought unto Solomon horses out of Egypt, and out of all lands." )
    , ( "Num 33:5", "And they departed from Ebronah, and encamped at Eziongaber." )
    , ( "Heb 11:8", "Of whom it was said, That in Isaac shall thy seed be called:" )
    , ( "Ch1 25:7", "The tenth to Shimei, he, his sons, and his brethren, were twelve:" )
    , ( "Isa 3:3", "The LORD standeth up to plead, and standeth to judge the people." )
    , ( "Gen 10:4", "And Pathrusim, and Casluhim, (out of whom came Philistim,) and Caphtorim." )
    , ( "Joh 6:8", "One of his disciples, Andrew, Simon Peter's brother, saith unto him," )
    , ( "Joh 2:2", "And both Jesus was called, and his disciples, to the marriage." )
    , ( "Ch1 12:6", "Elkanah, and Jesiah, and Azareel, and Joezer, and Jashobeam, the Korhites," )
    , ( "Gal 4:8", "Now we, brethren, as Isaac was, are the children of promise." )
    , ( "Jos 7:8", "O LORD, what shall I say, when Israel turneth their backs before their enemies!" )
    , ( "Gen 30:1", "And Leah said, A troop cometh: and she called his name Gad." )
    , ( "Act 26:5", "And I said, Who art thou, Lord? And he said, I am Jesus whom thou persecutest." )
    , ( "Zac 5:0", "Then said I to the angel that talked with me, Whither do these bear the ephah?" )
    , ( "Job 3:2", "Why did the knees prevent me? or why the breasts that I should suck?" )
    , ( "Rom 12:3", "Distributing to the necessity of saints; given to hospitality." )
    , ( "Mic 5:1", "And I will cut off the cities of thy land, and throw down all thy strong holds:" )
    , ( "Pro 10:4", "Wise men lay up knowledge: but the mouth of the foolish is near destruction." )
    , ( "Eph 6:4", "Grace be with all them that love our Lord Jesus Christ in sincerity. Amen." )
    , ( "Gen 38:0", "And the thing which he did displeased the LORD: wherefore he slew him also." )
    , ( "Ch1 24:2", "Of the Izharites; Shelomoth: of the sons of Shelomoth; Jahath." )
    , ( "Gen 49:2", "His eyes shall be red with wine, and his teeth white with milk." )
    , ( "Psa 47:8", "God reigneth over the heathen: God sitteth upon the throne of his holiness." )
    , ( "Psa 109:7", "That they may know that this is thy hand; that thou, LORD, hast done it." )
    , ( "Sol 1:9", "I have compared thee, O my love, to a company of horses in Pharaoh's chariots." )
    , ( "Plm 1:2", "Whom I have sent again: thou therefore receive him, that is, mine own bowels:" )
    , ( "Gen 30:3", "And she conceived, and bare a son; and said, God hath taken away my reproach:" )
    , ( "Col 3:4", " And above all these things put on charity, which is the bond of perfectness." )
    , ( "Num 19:1", "He that toucheth the dead body of any man shall be unclean seven days." )
    , ( "Mat 18:2", "And Jesus called a little child unto him, and set him in the midst of them," )
    , ( "Psa 69:5", "O God, thou knowest my foolishness; and my sins are not hid from thee." )
    , ( "Psa 31:5", "Into thine hand I commit my spirit: thou hast redeemed me, O LORD God of truth." )
    , ( "Joh 6:3", "And Jesus went up into a mountain, and there he sat with his disciples." )
    , ( "Luk 1:4", "And thou shalt have joy and gladness; and many shall rejoice at his birth." )
    , ( "Joh 1:0", "He was in the world, and the world was made by him, and the world knew him not." )
    , ( "Psa 136:1", "O give thanks unto the LORD; for he is good: for his mercy endureth for ever." )
    , ( "Kg2 6:7", "Therefore said he, Take it up to thee. And he put out his hand, and took it." )
    , ( "Kg2 25:2", "And the city was besieged unto the eleventh year of king Zedekiah." )
    , ( "Jo1 3:1", "Beloved, if our heart condemn us not, then have we confidence toward God." )
    , ( "Job 33:2", "Yea, his soul draweth near unto the grave, and his life to the destroyers." )
    , ( "Sol 6:7", "As a piece of a pomegranate are thy temples within thy locks." )
    , ( "Sa2 22:0", "He bowed the heavens also, and came down; and darkness was under his feet." )
    , ( "Psa 108:5", "Be thou exalted, O God, above the heavens: and thy glory above all the earth;" )
    , ( "Jon 2:0", "And the LORD spake unto the fish, and it vomited out Jonah upon the dry land." )
    , ( "Luk 13:3", "I tell you, Nay: but, except ye repent, ye shall all likewise perish." )
    , ( "Psa 115:6", "They have ears, but they hear not: noses have they, but they smell not:" )
    , ( "Psa 119:0", "Their heart is as fat as grease; but I delight in thy law." )
    , ( "Num 32:7", "And the children of Reuben built Heshbon, and Elealeh, and Kirjathaim," )
    , ( "Luk 13:9", "And if it bear fruit, well: and if not, then after that thou shalt cut it down." )
    , ( "Luk 1:5", "In holiness and righteousness before him, all the days of our life." )
    , ( "Jo3 1:3", "I had many things to write, but I will not with ink and pen write unto thee:" )
    , ( "Gen 49:0", "Out of Asher his bread shall be fat, and he shall yield royal dainties." )
    , ( "Mat 3:1", "In those days came John the Baptist, preaching in the wilderness of Judaea," )
    , ( "Sa2 14:1", "Now Joab the son of Zeruiah perceived that the king's heart was toward Absalom." )
    , ( "Psa 134:3", "The LORD that made heaven and earth bless thee out of Zion." )
    , ( "Joh 14:1", "Let not your heart be troubled: ye believe in God, believe also in me." )
    , ( "Ch1 2:7", "And Abigail bare Amasa: and the father of Amasa was Jether the Ishmeelite." )
    , ( "Num 7:8", "On the second day Nethaneel the son of Zuar, prince of Issachar, did offer:" )
    , ( "Psa 147:9", "He giveth to the beast his food, and to the young ravens which cry." )
    , ( "Th1 4:2", "For ye know what commandments we gave you by the Lord Jesus." )
    , ( "Psa 66:0", "Blessed be God, which hath not turned away my prayer, nor his mercy from me." )
    , ( "Neh 7:3", "The children of Bakbuk, the children of Hakupha, the children of Harhur," )
    , ( "Num 7:5", "One young bullock, one ram, one lamb of the first year, for a burnt offering:" )
    , ( "Rev 16:0", "And every island fled away, and the mountains were not found." )
    , ( "Jos 21:7", "Kedemoth with her suburbs, and Mephaath with her suburbs; four cities." )
    , ( "Pro 20:2", "The hearing ear, and the seeing eye, the LORD hath made even both of them." )
    , ( "Mar 5:1", "Now there was there nigh unto the mountains a great herd of swine feeding." )
    , ( "Sa1 6:1", "And the ark of the LORD was in the country of the Philistines seven months." )
    , ( "Num 7:1", "One young bullock, one ram, one lamb of the first year, for a burnt offering:" )
    , ( "Psa 89:3", "And I will beat down his foes before his face, and plague them that hate him." )
    , ( "Act 18:3", "Saying, This fellow persuadeth men to worship God contrary to the law." )
    , ( "Co1 11:9", "Neither was the man created for the woman; but the woman for the man." )
    , ( "Joh 15:3", "Now ye are clean through the word which I have spoken unto you." )
    , ( "Jer 13:2", "So I got a girdle according to the word of the LORD, and put it on my loins." )
    , ( "Exo 28:8", "And the second row shall be an emerald, a sapphire, and a diamond." )
    , ( "Jdg 17:1", "And there was a man of mount Ephraim, whose name was Micah." )
    , ( "Job 14:6", "For now thou numberest my steps: dost thou not watch over my sin?" )
    , ( "Mar 8:1", "And he said unto them, How is it that ye do not understand?" )
    , ( "Psa 106:3", "They soon forgat his works; they waited not for his counsel:" )
    , ( "Psa 83:8", "Assur also is joined with them: they have holpen the children of Lot. Selah." )
    , ( "Gal 6:2", "Bear ye one another's burdens, and so fulfil the law of Christ." )
    , ( "Mat 14:4", "And when they were gone over, they came into the land of Gennesaret." )
    , ( "Mat 11:4", "And if ye will receive it, this is Elias, which was for to come." )
    , ( "Gen 44:7", "And thy servant my father said unto us, Ye know that my wife bare me two sons:" )
    , ( "Joh 13:8", "Now no man at the table knew for what intent he spake this unto him." )
    , ( "Ch1 6:9", "And Aijalon with her suburbs, and Gathrimmon with her suburbs:" )
    , ( "Psa 145:9", "The LORD is good to all: and his tender mercies are over all his works." )
    , ( "Psa 110:7", "He shall drink of the brook in the way: therefore shall he lift up the head." )
    , ( "Phi 1:0", "Having the same conflict which ye saw in me, and now hear to be in me." )
    , ( "Ch1 1:9", "And the sons of Lotan; Hori, and Homam: and Timna was Lotan's sister." )
    , ( "Job 21:9", "Their houses are safe from fear, neither is the rod of God upon them." )
    , ( "Job 16:7", "Not for any injustice in mine hands: also my prayer is pure." )
    , ( "Gen 5:8", "And Lamech lived an hundred eighty and two years, and begat a son:" )
    , ( "Job 9:8", "He will not suffer me to take my breath, but filleth me with bitterness." )
    , ( "Job 7:7", "O remember that my life is wind: mine eye shall no more see good." )
    , ( "Heb 12:2", "Wherefore lift up the hands which hang down, and the feeble knees;" )
    , ( "Joh 14:8", "Philip saith unto him, Lord, shew us the Father, and it sufficeth us." )
    , ( "Kg1 4:2", "And these were the princes which he had; Azariah the son of Zadok the priest," )
    , ( "Tit 2:1", "For the grace of God that bringeth salvation hath appeared to all men," )
    , ( "Ch2 9:2", "And king Solomon passed all the kings of the earth in riches and wisdom." )
    , ( "Mat 14:7", "Whereupon he promised with an oath to give her whatsoever she would ask." )
    , ( "Deu 16:2", "Neither shalt thou set thee up any image; which the LORD thy God hateth." )
    , ( "Psa 106:8", "And a fire was kindled in their company; the flame burned up the wicked." )
    , ( "Pro 9:1", "Wisdom hath builded her house, she hath hewn out her seven pillars:" )
    , ( "Luk 23:2", "And there were also two other, malefactors, led with him to be put to death." )
    , ( "Co2 6:3", "Giving no offence in any thing, that the ministry be not blamed:" )
    , ( "Job 29:7", "And I brake the jaws of the wicked, and plucked the spoil out of his teeth." )
    , ( "Luk 20:8", "For he is not a God of the dead, but of the living: for all live unto him." )
    , ( "Eph 3:4", "Whereby, when ye read, ye may understand my knowledge in the mystery of Christ)" )
    , ( "Heb 3:1", "So I sware in my wrath, They shall not enter into my rest.)" )
    , ( "Psa 81:1", "Sing aloud unto God our strength: make a joyful noise unto the God of Jacob." )
    , ( "Deu 14:8", "And the stork, and the heron after her kind, and the lapwing, and the bat." )
    , ( "Pro 29:5", "A man that flattereth his neighbour spreadeth a net for his feet." )
    , ( "Lam 3:7", "He hath hedged me about, that I cannot get out: he hath made my chain heavy." )
    , ( "Pro 16:3", "Commit thy works unto the LORD, and thy thoughts shall be established." )
    , ( "Psa 139:3", "Search me, O God, and know my heart: try me, and know my thoughts:" )
    , ( "Luk 18:7", "And he said, The things which are impossible with men are possible with God." )
    , ( "Psa 35:5", "Let them be as chaff before the wind: and let the angel of the LORD chase them." )
    , ( "Act 6:0", "And they were not able to resist the wisdom and the spirit by which he spake." )
    , ( "Psa 78:1", "Yea, they turned back and tempted God, and limited the Holy One of Israel." )
    , ( "Eph 1:3", "Which is his body, the fulness of him that filleth all in all." )
    , ( "Pe1 3:1", "Let him eschew evil, and do good; let him seek peace, and ensue it." )
    , ( "Phi 3:7", "But what things were gain to me, those I counted loss for Christ." )
    , ( "Psa 84:9", "Behold, O God our shield, and look upon the face of thine anointed." )
    , ( "Psa 119:4", "Seven times a day do I praise thee because of thy righteous judgments." )
    , ( "Mat 14:4", "For John said unto him, It is not lawful for thee to have her." )
    , ( "Pro 2:8", "He keepeth the paths of judgment, and preserveth the way of his saints." )
    , ( "Rom 8:2", "Therefore, brethren, we are debtors, not to the flesh, to live after the flesh." )
    , ( "Num 3:4", "And the LORD spake unto Moses in the wilderness of Sinai, saying," )
    , ( "Jer 1:6", "Then said I, Ah, Lord GOD! behold, I cannot speak: for I am a child." )
    , ( "Ch2 28:6", "At that time did king Ahaz send unto the kings of Assyria to help him." )
    , ( "Sa2 24:9", "And David, according to the saying of Gad, went up as the LORD commanded." )
    , ( "Sol 4:5", "A fountain of gardens, a well of living waters, and streams from Lebanon." )
    , ( "Psa 3:3", "But thou, O LORD, art a shield for me; my glory, and the lifter up of mine head." )
    , ( "Ch1 2:9", "And when Azubah was dead, Caleb took unto him Ephrath, which bare him Hur." )
    , ( "Psa 33:1", "Rejoice in the LORD, O ye righteous: for praise is comely for the upright." )
    , ( "Psa 142:2", "I poured out my complaint before him; I shewed before him my trouble." )
    , ( "Co2 1:2", "Who hath also sealed us, and given the earnest of the Spirit in our hearts." )
    , ( "Mar 4:8", "And these are they which are sown among thorns; such as hear the word," )
    , ( "Job 9:7", "Which commandeth the sun, and it riseth not; and sealeth up the stars." )
    , ( "Gen 42:2", "And he said unto them, Nay, but to see the nakedness of the land ye are come." )
    , ( "Psa 103:8", "The LORD is merciful and gracious, slow to anger, and plenteous in mercy." )
    , ( "Joh 12:1", "These things said Esaias, when he saw his glory, and spake of him." )
    , ( "Psa 9:7", "But the LORD shall endure for ever: he hath prepared his throne for judgment." )
    , ( "Pro 6:3", "A wound and dishonour shall he get; and his reproach shall not be wiped away." )
    , ( "Joh 6:0", "Jesus answered them, Have not I chosen you twelve, and one of you is a devil?" )
    , ( "Mat 20:5", "Again he went out about the sixth and ninth hour, and did likewise." )
    , ( "Job 37:9", "Out of the south cometh the whirlwind: and cold out of the north." )
    , ( "Luk 14:2", "And, behold, there was a certain man before him which had the dropsy." )
    , ( "Exo 25:6", "And thou shalt put into the ark the testimony which I shall give thee." )
    , ( "Rut 4:8", "Therefore the kinsman said unto Boaz, Buy it for thee. So he drew off his shoe." )
    , ( "Isa 12:3", "Therefore with joy shall ye draw water out of the wells of salvation." )
    , ( "Pro 2:3", "Who leave the paths of uprightness, to walk in the ways of darkness;" )
    , ( "Act 19:8", "And many that believed came, and confessed, and shewed their deeds." )
    , ( "Exo 29:5", "And I will dwell among the children of Israel, and will be their God." )
    , ( "Joh 15:2", "This is my commandment, That ye love one another, as I have loved you." )
    , ( "Psa 51:9", "Hide thy face from my sins, and blot out all mine iniquities." )
    , ( "Jam 2:2", "So speak ye, and so do, as they that shall be judged by the law of liberty." )
    , ( "Psa 119:4", "Thou art my hiding place and my shield: I hope in thy word." )
    , ( "Th1 4:7", "For God hath not called us unto uncleanness, but unto holiness." )
    , ( "Exo 26:2", "And for the sides of the tabernacle westward thou shalt make six boards." )
    , ( "Exo 36:7", "And for the sides of the tabernacle westward he made six boards." )
    , ( "Psa 97:6", "The heavens declare his righteousness, and all the people see his glory." )
    , ( "Ezr 2:2", "The children of Bazluth, the children of Mehida, the children of Harsha," )
    , ( "Gen 36:4", "And Jobab died, and Husham of the land of Temani reigned in his stead." )
    , ( "Ch1 24:7", "The one and twentieth to Jachin, the two and twentieth to Gamul," )
    , ( "Luk 21:2", "And he saw also a certain poor widow casting in thither two mites." )
    , ( "Psa 3:2", "Many there be which say of my soul, There is no help for him in God. Selah." )
    , ( "Mat 15:0", "And he called the multitude, and said unto them, Hear, and understand:" )
    , ( "Job 36:6", "He preserveth not the life of the wicked: but giveth right to the poor." )
    , ( "Isa 43:8", "Bring forth the blind people that have eyes, and the deaf that have ears." )
    , ( "Jer 14:1", "Then said the LORD unto me, Pray not for this people for their good." )
    , ( "Gen 9:9", "And all the days of Noah were nine hundred and fifty years: and he died." )
    , ( "Phi 2:0", "For I have no man likeminded, who will naturally care for your state." )
    , ( "Gen 7:5", "And Noah did according unto all that the LORD commanded him." )
    , ( "Jon 1:1", "Now the word of the LORD came unto Jonah the son of Amittai, saying," )
    , ( "Luk 12:4", "Of a truth I say unto you, that he will make him ruler over all that he hath." )
    , ( "Jer 38:1", "But if thou refuse to go forth, this is the word that the LORD hath shewed me:" )
    , ( "Psa 116:2", "What shall I render unto the LORD for all his benefits toward me?" )
    , ( "Jam 1:3", "Knowing this, that the trying of your faith worketh patience." )
    , ( "Psa 22:9", "But be not thou far from me, O LORD: O my strength, haste thee to help me." )
    , ( "Rom 6:0", "For when ye were the servants of sin, ye were free from righteousness." )
    , ( "Hos 10:7", "As for Samaria, her king is cut off as the foam upon the water." )
    , ( "Ch1 6:7", "And these be the names of the sons of Gershom; Libni, and Shimei." )
    , ( "Pro 23:4", "Thou shalt beat him with the rod, and shalt deliver his soul from hell." )
    , ( "Psa 76:9", "When God arose to judgment, to save all the meek of the earth. Selah." )
    , ( "Deu 19:7", "Wherefore I command thee, saying, Thou shalt separate three cities for thee." )
    , ( "Hos 13:5", "I did know thee in the wilderness, in the land of great drought." )
    , ( "Act 23:6", "Claudius Lysias unto the most excellent governor Felix sendeth greeting." )
    , ( "Job 6:8", "Now therefore be content, look upon me; for it is evident unto you if I lie." )
    , ( "Mar 10:0", "And he, casting away his garment, rose, and came to Jesus." )
    , ( "Gen 32:7", "And he said unto him, What is thy name? And he said, Jacob." )
    , ( "Pro 22:4", "By humility and the fear of the LORD are riches, and honour, and life." )
    , ( "Th1 1:7", "So that ye were ensamples to all that believe in Macedonia and Achaia." )
    , ( "Luk 14:0", "Saying, This man began to build, and was not able to finish." )
    , ( "Job 34:4", "Let men of understanding tell me, and let a wise man hearken unto me." )
    , ( "Phi 3:1", "If by any means I might attain unto the resurrection of the dead." )
    , ( "Jos 12:9", "The king of Jericho, one; the king of Ai, which is beside Bethel, one;" )
    , ( "Luk 1:0", "And his mercy is on them that fear him from generation to generation." )
    , ( "Psa 92:5", "O LORD, how great are thy works! and thy thoughts are very deep." )
    , ( "Neh 11:6", "And of the Levites were divisions in Judah, and in Benjamin." )
    , ( "Joh 11:8", "Now Bethany was nigh unto Jerusalem, about fifteen furlongs off:" )
    , ( "Psa 89:3", "I have made a covenant with my chosen, I have sworn unto David my servant," )
    , ( "Neh 11:8", "All the Levites in the holy city were two hundred fourscore and four." )
    , ( "Pe1 3:3", "And who is he that will harm you, if ye be followers of that which is good?" )
    , ( "Gen 2:5", "And they were both naked, the man and his wife, and were not ashamed." )
    , ( "Psa 73:1", "Truly God is good to Israel, even to such as are of a clean heart." )
    , ( "Num 22:9", "And Balaam went with Balak, and they came unto Kirjathhuzoth." )
    , ( "Mat 15:5", "Then answered Peter and said unto him, Declare unto us this parable." )
    , ( "Psa 119:3", "Teach me, O LORD, the way of thy statutes; and I shall keep it unto the end." )
    , ( "Sa1 19:2", "So Michal let David down through a window: and he went, and fled, and escaped." )
    , ( "Kg1 13:7", "And he spake to his sons, saying, Saddle me the ass. And they saddled him." )
    , ( "Mat 23:6", "And love the uppermost rooms at feasts, and the chief seats in the synagogues," )
    , ( "Hag 1:3", "Then came the word of the LORD by Haggai the prophet, saying," )
    , ( "Sol 2:5", "Stay me with flagons, comfort me with apples: for I am sick of love." )
    , ( "Joh 5:7", "But Jesus answered them, My Father worketh hitherto, and I work." )
    , ( "Psa 37:3", "The LORD shall laugh at him: for he seeth that his day is coming." )
    , ( "Gen 13:3", "But the men of Sodom were wicked and sinners before the LORD exceedingly." )
    , ( "Job 8:1", "Can the rush grow up without mire? can the flag grow without water?" )
    , ( "Psa 107:9", "For he satisfieth the longing soul, and filleth the hungry soul with goodness." )
    , ( "Luk 24:1", "And their words seemed to them as idle tales, and they believed them not." )
    , ( "Job 41:2", "In his neck remaineth strength, and sorrow is turned into joy before him." )
    , ( "Mat 4:1", "Then the devil leaveth him, and, behold, angels came and ministered unto him." )
    , ( "Gen 5:1", "And Enoch lived sixty and five years, and begat Methuselah:" )
    , ( "Psa 119:4", "Deliver me from the oppression of man: so will I keep thy precepts." )
    , ( "Psa 105:5", "He turned their heart to hate his people, to deal subtilly with his servants." )
    , ( "Joh 12:0", "But the chief priests consulted that they might put Lazarus also to death;" )
    , ( "Job 13:3", "Surely I would speak to the Almighty, and I desire to reason with God." )
    , ( "Lev 24:4", "He shall order the lamps upon the pure candlestick before the LORD continually." )
    , ( "Pro 11:4", "Riches profit not in the day of wrath: but righteousness delivereth from death." )
    , ( "Psa 72:2", "He shall judge thy people with righteousness, and thy poor with judgment." )
    , ( "Mat 25:1", "Afterward came also the other virgins, saying, Lord, Lord, open to us." )
    , ( "Ch1 25:1", "The fourth to Izri, he, his sons, and his brethren, were twelve:" )
    , ( "Rom 12:7", "Or ministry, let us wait on our ministering: or he that teacheth, on teaching;" )
    , ( "Jer 13:3", "And the word of the LORD came unto me the second time, saying," )
    , ( "Pro 31:1", "The words of king Lemuel, the prophecy that his mother taught him." )
    , ( "Lev 26:7", "And ye shall chase your enemies, and they shall fall before you by the sword." )
    , ( "Psa 105:7", "They shewed his signs among them, and wonders in the land of Ham." )
    , ( "Mat 15:1", "Then Jesus went thence, and departed into the coasts of Tyre and Sidon." )
    , ( "Lam 3:3", "He hath caused the arrows of his quiver to enter into my reins." )
    , ( "Ch1 26:3", "Of the Amramites, and the Izharites, the Hebronites, and the Uzzielites:" )
    , ( "Ch1 9:0", "And the son of Jonathan was Meribbaal: and Meribbaal begat Micah." )
    , ( "Psa 90:7", "For we are consumed by thine anger, and by thy wrath are we troubled." )
    , ( "Mat 14:5", "And in the fourth watch of the night Jesus went unto them, walking on the sea." )
    , ( "Ecc 2:4", "I made me great works; I builded me houses; I planted me vineyards:" )
    , ( "Psa 26:6", "I will wash mine hands in innocency: so will I compass thine altar, O LORD:" )
    , ( "Tit 3:6", "Which he shed on us abundantly through Jesus Christ our Saviour;" )
    , ( "Pro 29:1", "A fool uttereth all his mind: but a wise man keepeth it in till afterwards." )
    , ( "Ecc 7:9", "Wisdom strengtheneth the wise more than ten mighty men which are in the city." )
    , ( "Pro 8:3", "I was set up from everlasting, from the beginning, or ever the earth was." )
    , ( "Ezr 2:5", "The children of Senaah, three thousand and six hundred and thirty." )
    , ( "Mat 26:6", "Now when Jesus was in Bethany, in the house of Simon the leper," )
    , ( "Ch1 7:1", "Now the sons of Issachar were, Tola, and Puah, Jashub, and Shimrom, four." )
    , ( "Deu 6:6", "And these words, which I command thee this day, shall be in thine heart:" )
    , ( "Job 3:8", "There the prisoners rest together; they hear not the voice of the oppressor." )
    , ( "Gal 3:4", "Have ye suffered so many things in vain? if it be yet in vain." )
    , ( "Num 28:9", "A several tenth deal unto one lamb, throughout the seven lambs;" )
    , ( "Eze 48:9", "And they that serve the city shall serve it out of all the tribes of Israel." )
    , ( "Gen 4:3", "And Cain said unto the LORD, My punishment is greater than I can bear." )
    , ( "Psa 29:1", "Give unto the LORD, O ye mighty, give unto the LORD glory and strength." )
    , ( "Num 23:5", "And Balak said unto Balaam, Neither curse them at all, nor bless them at all." )
    , ( "Jer 13:5", "So I went, and hid it by Euphrates, as the LORD commanded me." )
    , ( "Psa 148:8", "Fire, and hail; snow, and vapours; stormy wind fulfilling his word:" )
    , ( "Pro 30:2", "Surely I am more brutish than any man, and have not the understanding of a man." )
    , ( "Luk 23:4", "And that day was the preparation, and the sabbath drew on." )
    , ( "Psa 119:2", "Mine eyes fail for thy word, saying, When wilt thou comfort me?" )
    , ( "Gen 10:8", "And Cush begat Nimrod: he began to be a mighty one in the earth." )
    , ( "Mat 13:7", "And some fell among thorns; and the thorns sprung up, and choked them:" )
    , ( "Job 28:8", "The lion's whelps have not trodden it, nor the fierce lion passed by it." )
    , ( "Psa 119:7", "I am afflicted very much: quicken me, O LORD, according unto thy word." )
    ]


benignTextsEnglish : List ( String, String )
benignTextsEnglish =
    [ ( "", "random bla bla" )
    , ( "", "nonsense bla bla" )
    ]


documentsGerman : List Document
documentsGerman =
    List.map (uncurry (Document God)) divineTextsGerman
        ++ List.map (uncurry (Document God)) benignTextsGerman


divineTextsGerman : List ( String, String )
divineTextsGerman =
    [ ( "Psa 78:48", "da er ihr Vieh schlug mit Hagel und ihre Herden mit Wetterstrahlen;" )
    , ( "1Co 2:15", "Der geistliche aber richtet alles, und wird von niemand gerichtet." )
    , ( "Psa 103:2", "Lobe den HErrn, meine Seele, und vergiss nicht, was er dir Gutes getan hat:" )
    , ( "Dan 8:2", "Ich war aber in solchem Gesicht zu Schloss Susan im Lande Elam, am Wasser Ulai." )
    , ( "1Ki 13:30", "Und er legte den Leichnam in sein Grab; und sie beklagten ihn: Ach, Bruder!" )
    , ( "Luk 23:17", "(Denn er musste ihnen einen nach der Gewohnheit des Festes losgeben.)" )
    , ( "Mat 24:42", "Darum wachet, denn ihr wisset nicht, welche Stunde euer Herr kommen wird." )
    , ( "1Ch 3:17", "Die Kinder aber Jechonjas, der gefangen ward, waren Sealthiel," )
    , ( "Job 22:4", "Meinst du wegen deiner Gottesfurcht strafe er dich und gehe mit dir ins Gericht?" )
    , ( "Joh 3:9", "Nikodemus antwortete und sprach zu ihm: Wie mag solches zugehen?" )
    , ( "Pro 25:25", "Eine gute Botschaft aus fernen Landen ist wie kalt Wasser einer durstigen Seele." )
    , ( "1Ki 18:17", "Und da Ahab Elia sah, sprach Ahab zu ihm: Bist du, der Israel verwirrt?" )
    , ( "Mat 10:7", "Geht aber und predigt und sprecht: Das Himmelreich ist nahe herbeigekommen." )
    , ( "Psa 147:9", "der dem Vieh sein Futter gibt, den jungen Raben, die ihn anrufen." )
    , ( "Gal 3:27", "Denn wieviel euer auf Christum getauft sind, die haben Christum angezogen." )
    , ( "Act 10:26", "Petrus aber richtete ihn auf und sprach: Stehe auf, ich bin auch ein Mensch." )
    , ( "Psa 106:35", "sondern sie mengten sich unter die Heiden und lernten derselben Werke" )
    , ( "Rev 17:13", "Die haben eine Meinung und werden ihre Kraft und Macht geben dem Tier." )
    , ( "Joh 1:44", "Philippus aber war von Bethsaida, aus der Stadt des Andreas und Petrus." )
    , ( "Pro 21:30", "Es hilft keine Weisheit, kein Verstand, kein Rat wider den HErrn." )
    , ( "Num 34:10", "Und sollt messen die Grenze gegen Morgen vom Dorf Enan gen Sepham," )
    , ( "Job 28:2", "Eisen bringt man aus der Erde, und aus den Steinen schmelzt man Erz." )
    , ( "Rev 2:15", "Also hast du auch, die an der Lehre der Nikolaiten halten: das hasse ich." )
    , ( "Deu 31:22", "Also schrieb Mose dieses Lied zur selben Zeit und lehrte es die Kinder Israel." )
    , ( "Job 21:4", "Handle ich denn mit einem Menschen? oder warum sollte ich ungeduldig sein?" )
    , ( "Psa 81:5", "Denn solches ist die Weise in Israel und ein Recht des Gottes Jakobs." )
    , ( "Mat 5:8", "Selig sind, die reines Herzens sind; denn sie werden Gott schauen." )
    , ( "Num 20:28", "Und Mose zog Aaron seine Kleider aus und zog sie Eleasar an, seinem Sohne." )
    , ( "Heb 10:14", "Denn mit einem Opfer hat er in Ewigkeit vollendet, die geheiligt werden." )
    , ( "Jdg 20:24", "Und da die Kinder Israel sich machten an die Kinder Benjamin des andern Tages," )
    , ( "Psa 108:14", "Mit Gott wollen wir Taten tun; er wird unsre Feinde untertreten." )
    , ( "Mat 26:72", "Und er leugnete abermals und schwur dazu: Ich kenne den Menschen nicht." )
    , ( "Jer 13:5", "Ich ging hin und versteckte ihn am Euphrat, wie mir der HErr geboten hatte." )
    , ( "Psa 139:3", "Ich gehe oder liege, so bist du um mich und siehest alle meine Wege." )
    , ( "Jos 9:14", "Da nahmen die Hauptleute ihre Speise an und fragten den Mund des HErrn nicht." )
    , ( "Dan 7:15", "Ich, Daniel, entsetzte mich davor, und solches Gesicht erschreckte mich." )
    , ( "Act 28:24", "Und etliche fielen dem zu, was er sagte; etliche aber glaubten nicht." )
    , ( "Lev 26:7", "Ihr sollt eure Feinde jagen, und sie sollen vor euch her ins Schwert fallen." )
    , ( "Deu 31:25", "gebot er den Leviten, die die Lade des Zeugnisses des HErrn trugen, und sprach:" )
    , ( "Psa 52:6", "Du redest gerne alles, was zu verderben dient, mit falscher Zunge." )
    , ( "Exo 37:5", "und tat sie in die Ringe an der Lade Seiten, dass man sie tragen konnte." )
    , ( "Mat 24:46", "Selig ist der Knecht, wenn sein Herr kommt und findet ihn also tun." )
    , ( "Lev 12:3", "Und am achten Tage soll man das Fleisch seiner Vorhaut beschneiden." )
    , ( "Pro 3:8", "Das wird deinem Leibe gesund sein und deine Gebeine erquicken." )
    , ( "Job 41:20", "Kein Pfeil wird ihn verjagen; die Schleudersteine sind ihm wie Stoppeln." )
    , ( "1Ch 8:9", "und er zeugte von Hodes, seinem Weibe: Jobab, Zibja, Mesa, Malcham," )
    , ( "Num 27:23", "und legte seine Hand auf ihn und gebot ihm, wie der HErr mit Mose geredet hatte." )
    , ( "1Th 2:6", "haben auch nicht Ehre gesucht von den Leuten, weder von euch noch von andern;" )
    , ( "Deu 23:1", "Niemand soll seines Vaters Weib nehmen und nicht aufdecken seines Vaters Decke." )
    , ( "Psa 81:12", "Aber mein Volk gehorcht nicht meiner Stimme, und Israel will mich nicht." )
    , ( "1Ch 24:27", "Die Kinder Meraris von Jaesia, seinem Sohn, waren: Soham, Sakkur und Ibri." )
    , ( "2Ki 8:11", "Und der Mann Gottes schaute ihn starr und lange an und weinte." )
    , ( "Pro 3:30", "Hadere nicht mit jemand ohne Ursache, so er dir kein Leid getan hat." )
    , ( "1Ch 7:6", "Die Kinder Benjamins waren Bela, Becher und Jediael, die drei." )
    , ( "Exo 4:22", "Und du sollst zu ihm sagen: So sagt der HErr: Israel ist mein erstgeborener Sohn;" )
    , ( "Luk 8:53", "Und sie verlachten ihn, wussten wohl, dass sie gestorben war." )
    , ( "Lev 18:2", "Rede mit den Kindern Israel und sprich zu ihnen: Ich bin der HErr, euer Gott." )
    , ( "Ecc 5:19", "Denn er denkt nicht viel an die Tage seines Lebens, weil Gott sein Herz erfreut." )
    , ( "Psa 119:25", "Meine Seele liegt im Staube; erquicke mich nach deinem Wort." )
    , ( "Job 17:16", "Hinunter zu den Toten wird es fahren und wird mit mir in dem Staub liegen." )
    , ( "Psa 150:4", "Lobet ihn mit Pauken und Reigen; lobet ihn mit Saiten und Pfeifen!" )
    , ( "Mar 11:30", "Die Taufe des Johannes, war sie vom Himmel oder von den Menschen? Antwortet mir!" )
    , ( "1Co 15:8", "Am letzten ist er auch von mir, einer unzeitigen Geburt gesehen worden." )
    , ( "Luk 7:1", "Nachdem er aber vor dem Volk ausgeredet hatte, ging er gen Kapernaum." )
    , ( "Psa 118:11", "Sie umgeben mich allenthalben; aber im Namen des HErrn will ich sie zerhauen." )
    , ( "Lev 13:14", "Ist aber rohes Fleisch da des Tages, wenn er besehen wird, so ist er unrein." )
    , ( "Luk 22:17", "Und er nahm den Kelch, dankte und sprach: Nehmet ihn und teilet ihn unter euch;" )
    , ( "1Ch 7:18", "Und seine Schwester Molecheth gebar Ishod, Abieser und Mahela." )
    , ( "Mat 22:43", "Er sprach zu ihnen: Wie nennt ihn denn David im Geist einen Herrn, da er sagt:" )
    , ( "1Ch 3:23", "Die Kinder aber Nearjas waren: Eljoenai, Hiskia, Asrikam, die drei." )
    , ( "2Sa 22:22", "Denn ich halte die Wege des HErrn und bin nicht gottlos wider meinen Gott." )
    , ( "Luk 11:40", "Ihr Narren, meinet ihr, dass es inwendig rein sei, wenn's auswendig rein ist?" )
    , ( "Joh 8:45", "Ich aber, weil ich die Wahrheit sage, so glaubet ihr mir nicht." )
    , ( "Col 2:6", "Wie ihr nun angenommen habt den Herrn Christus Jesus, so wandelt in ihm" )
    , ( "Luk 22:57", "Er aber verleugnete ihn und sprach: Weib, ich kenne ihn nicht." )
    , ( "Psa 1:2", "sondern hat Lust zum Gesetz des HErrn und redet von seinem Gesetz Tag und Nacht!" )
    , ( "Mat 22:35", "Und einer unter ihnen, ein Schriftgelehrter, versuchte ihn und sprach:" )
    , ( "2Co 6:11", "O ihr Korinther! unser Mund hat sich zu euch aufgetan, unser Herz ist weit." )
    , ( "Eze 7:25", "Der Ausrotter kommt; da werden sie Frieden suchen, und wird keiner dasein." )
    , ( "Job 5:27", "Siehe, das haben wir erforscht und ist also; dem gehorche und merke du dir's." )
    , ( "Gen 15:8", "Abram aber sprach: HERR, woran soll ich merken, dass ich's besitzen werde?" )
    , ( "Pro 5:7", "So gehorchet mir nun, meine Kinder, und weichet nicht von der Rede meines Mundes." )
    , ( "Heb 9:27", "Und wie den Menschen gesetzt ist, einmal zu sterben, darnach aber das Gericht:" )
    , ( "Job 36:29", "Wenn er sich vornimmt die Wolken auszubreiten wie sein hoch Gezelt," )
    , ( "Job 31:38", "Wird mein Land gegen mich schreien und werden miteinander seine Furchen weinen;" )
    , ( "Mar 14:33", "Und nahm Petrus und Jakobus und Johannes und fing an, zu zittern und zu zagen." )
    , ( "Rev 19:3", "Und sie sprachen zum andernmal: Halleluja! und der Rauch geht auf ewiglich." )
    , ( "Neh 7:46", "Die Tempelknechte: die Kinder Ziha, die Kinder Hasupha, die Kinder Tabbaoth," )
    , ( "1Ki 20:18", "Er sprach: Greift sie lebendig, sie seien um Friedens oder um Streit ausgezogen!" )
    , ( "1Ch 4:16", "Die Kinder aber Jehallel-Els waren Siph, Sipha, Thirja und Asareel." )
    , ( "Mat 28:17", "Und da sie ihn sahen, fielen sie vor ihm nieder; etliche aber zweifelten." )
    , ( "Deu 1:2", "Elf Tagereisen von Horeb, durch den Weg des Gebirges Seir, bis gen Kades-Barnea." )
    , ( "Psa 119:55", "HErr, ich gedenke des Nachts an deinen Namen und halte dein Gesetz." )
    , ( "Joh 2:24", "Aber Jesus vertraute sich ihnen nicht; denn er kannte sie alle" )
    , ( "Psa 115:14", "Der HErr segne euch je mehr und mehr, euch und eure Kinder!" )
    , ( "Psa 100:2", "Dienet dem HErrn mit Freuden; kommt vor sein Angesicht mit Frohlocken!" )
    , ( "Gen 27:44", "und bleib eine Weile bei ihm, bis sich der Grimm deines Bruders legt" )
    , ( "Ecc 3:2", "Geboren werden und sterben, pflanzen und ausrotten, was gepflanzt ist," )
    , ( "2Ch 14:11", "Und der HErr schlug die Mohren vor Asa und vor Juda, dass sie flohen." )
    , ( "Pro 28:23", "Wer einen Menschen straft, wird hernach Gunst finden, mehr denn der da heuchelt." )
    , ( "Pro 8:35", "Wer mich findet, der findet das Leben und wird Wohlgefallen vom HErrn erlangen." )
    , ( "Rom 9:18", "So erbarmt er sich nun, welches er will, und verstockt, welchen er will." )
    , ( "Psa 102:29", "Die Kinder deiner Knechte werden bleiben, und ihr Same wird vor dir gedeihen." )
    , ( "Pro 15:1", "Eine linde Antwort stillt den Zorn; aber ein hartes Wort richtet Grimm an." )
    , ( "1Co 4:2", "Nun sucht man nicht mehr an den Haushaltern, denn dass sie treu erfunden werden." )
    , ( "Lev 26:14", "Werdet ihr aber mir nicht gehorchen und nicht tun diese Gebote alle" )
    , ( "Psa 134:3", "Der HErr segne dich aus Zion, der Himmel und Erde gemacht hat!" )
    , ( "Psa 12:4", "Der HErr wolle ausrotten alle Heuchelei und die Zunge, die da stolz redet," )
    , ( "Rom 7:16", "So ich aber das tue, was ich nicht will, so gebe ich zu, dass das Gesetz gut sei." )
    , ( "Deu 9:24", "Denn ihr seid ungehorsam dem HErrn gewesen, solange ich euch gekannt habe." )
    , ( "Jon 2:11", "Und der HErr sprach zum Fisch, und der spie Jona aus ans Land." )
    , ( "1Ch 2:43", "Die Kinder aber Hebrons sind: Korah, Tappuah, Rekem und Sama." )
    , ( "Lam 3:30", "und lasse sich auf die Backen schlagen und viel Schmach anlegen." )
    , ( "Luk 6:5", "Und er sprach zu ihnen: Des Menschen Sohn ist ein Herr auch des Sabbats." )
    , ( "Exo 38:29", "Das Webeopfer aber des Erzes war siebzig Zentner zweitausendvierhundert Lot." )
    , ( "Act 11:2", "Und da Petrus hinaufkam gen Jerusalem, zankten mit ihm, die aus den Juden waren," )
    , ( "Deu 2:3", "Ihr habt dies Gebirge nun genug umzogen; wendet euch gegen Mitternacht." )
    , ( "Psa 107:27", "dass sie taumelten und wankten wie ein Trunkener und wussten keinen Rat mehr;" )
    , ( "Psa 67:3", "dass man auf Erden erkenne seinen Weg, unter allen Heiden sein Heil." )
    , ( "Deu 22:11", "Du sollst nicht anziehen ein gemengtes Kleid, von Wolle und Leinen zugleich." )
    , ( "Psa 29:4", "Die Stimme des HErrn geht mit Macht; die Stimme des HErrn geht herrlich." )
    , ( "Joh 9:36", "Er antwortete und sprach: Herr, welcher ist's? auf dass ich an ihn glaube." )
    , ( "Phi 2:8", "er erniedrigte sich selbst und ward gehorsam bis zum Tode, ja zum Tode am Kreuz." )
    , ( "Job 40:13", "Verscharre sie miteinander in die Erde und versenke ihre Pracht ins Verborgene," )
    , ( "Lam 3:37", "Wer darf denn sagen, dass solches geschehe ohne des HErrn Befehl" )
    , ( "Rom 10:2", "Denn ich gebe ihnen das Zeugnis, dass sie eifern um Gott, aber mit Unverstand." )
    , ( "Eze 24:20", "Und ich sprach zu ihnen: Der HErr hat mir geredet und gesagt:" )
    , ( "Deu 32:3", "Denn ich will den Namen des HErrn preisen. Gebt unsrem Gott allein die Ehre!" )
    , ( "Job 6:3", "Denn nun ist es schwerer als Sand am Meer; darum gehen meine Worte irre." )
    , ( "Luk 4:32", "Und sie verwunderten sich seiner Lehre; denn seine Rede war gewaltig." )
    , ( "Mat 8:5", "Da aber Jesus einging zu Kapernaum, trat ein Hauptmann zu ihm, der bat ihn" )
    , ( "Psa 44:26", "Denn unsre Seele ist gebeugt zur Erde; unser Leib klebt am Erdboden." )
    , ( "Job 26:6", "Das Grab ist aufgedeckt vor ihm, und der Abgrund hat keine Decke." )
    , ( "Gen 21:34", "Und er war ein Fremdling in der Philister Lande eine lange Zeit." )
    , ( "Psa 87:3", "Herrliche Dinge werden in dir gepredigt, du Stadt Gottes. (Sela.)" )
    , ( "Isa 7:21", "Zu derselben Zeit wird ein Mann eine junge Kuh und zwei Schafe ziehen" )
    , ( "Mat 24:18", "und wer auf dem Felde ist, der kehre nicht um, seine Kleider zu holen." )
    , ( "Luk 1:23", "Und es begab sich, da die Zeit seines Amts aus war, ging er heim in sein Haus." )
    , ( "Luk 1:67", "Und sein Vater Zacharias ward des heiligen Geistes voll, weissagte und sprach:" )
    , ( "Sol 3:7", "Siehe, um das Bett Salomos her stehen sechzig Starke aus den Starken in Israel." )
    , ( "Phi 4:23", "Die Gnade unsres Herrn Jesu Christi sei mit euch allen! Amen." )
    , ( "Joh 8:50", "Ich suche nicht meine Ehre; es ist aber einer, der sie sucht, und richtet." )
    , ( "Mat 27:8", "Daher ist dieser Acker genannt der Blutacker bis auf den heutigen Tag." )
    , ( "Gal 3:26", "Denn ihr seid alle Gottes Kinder durch den Glauben an Christum Jesum." )
    , ( "Psa 120:6", "Es wird meiner Seele lang, zu wohnen bei denen, die den Frieden hassen." )
    , ( "Pro 3:16", "Langes Leben ist zu ihrer rechten Hand; zu ihrer Linken ist Reichtum und Ehre." )
    , ( "1Ch 24:24", "Die Kinder Usiels waren: Micha. Unter den Kindern Michas war Samir." )
    , ( "Joh 13:25", "Denn derselbe lag an der Brust Jesu, und er sprach zu ihm: Herr, wer ist's?" )
    , ( "Luk 11:16", "Die andern aber versuchten ihn und begehrten ein Zeichen von ihm vom Himmel." )
    , ( "Lam 3:24", "Der HErr ist mein Teil, spricht meine Seele; darum will ich auf ihn hoffen." )
    , ( "Sol 8:3", "Seine Linke liegt unter meinem Haupt, und seine Rechte herzt mich." )
    , ( "Psa 30:5", "Ihr Heiligen, lobsinget dem HErrn; danket und preiset seine Heiligkeit!" )
    , ( "2Sa 15:33", "Und David sprach zu ihm: Wenn du mit mir gehst, wirst du mir eine Last sein." )
    , ( "Eze 43:4", "Und die Herrlichkeit des HErrn kam hinein zum Hause durchs Tor gegen Morgen." )
    , ( "Eze 5:3", "Nimm aber ein klein wenig davon und binde es in deinen Mantelzipfel." )
    , ( "Heb 13:16", "Wohlzutun und mitzuteilen vergesset nicht; denn solche Opfer gefallen Gott wohl." )
    , ( "Num 22:2", "Und Balak, der Sohn Zippors, sah alles, was Israel getan hatte den Amoritern;" )
    , ( "2Sa 22:50", "Darum will ich dir danken, HErr, unter den Heiden und deinem Namen lobsingen," )
    , ( "Luk 7:50", "Er aber sprach zu dem Weibe: Dein Glaube hat dir geholfen; gehe hin mit Frieden!" )
    , ( "Exo 7:23", "Und Pharao wandte sich und ging heim und nahm's nicht zu Herzen." )
    , ( "Psa 31:15", "Ich aber, HErr, hoffe auf dich und spreche: Du bist mein Gott!" )
    , ( "Psa 33:20", "Unsre Seele harret auf den HErrn; er ist unsre Hilfe und Schild." )
    , ( "Hag 2:11", "So spricht der HErr Zebaoth: Frage die Priester um das Gesetz und sprich:" )
    , ( "Gen 36:25", "Die Kinder aber Anas waren: Dison und Oholibama, das ist die Tochter Anas." )
    , ( "Exo 25:14", "und stecke sie in die Ringe an der Lade Seiten, dass man sie damit trage;" )
    , ( "Jon 1:1", "Es geschah das Wort des HErrn zu Jona, dem Sohn Amitthais, und sprach:" )
    , ( "Psa 84:5", "Wohl denen, die in deinem Hause wohnen; die loben dich immerdar. (Sela.)" )
    , ( "Col 3:2", "Trachtet nach dem, was droben ist, nicht nach dem, was auf Erden ist." )
    , ( "Job 9:7", "Er spricht zur Sonne, so geht sie nicht auf, und versiegelt die Sterne." )
    , ( "1Ki 21:17", "Aber das Wort des HErrn kam zu Elia, dem Thisbiter, und sprach:" )
    , ( "1Ch 11:35", "Ahiam, der Sohn Sachars, der Harariter; Elipal der Sohn Urs;" )
    , ( "Psa 57:8", "Mein Herz ist bereit, Gott, mein Herz ist bereit, dass ich singe und lobe." )
    , ( "Luk 24:26", "Musste nicht Christus solches leiden und zu seiner Herrlichkeit eingehen?" )
    , ( "Isa 40:17", "Alle Heiden sind vor ihm nichts und wie ein Nichtiges und Eitles geachtet." )
    , ( "Psa 90:16", "Zeige deinen Knechten deine Werke und deine Ehre ihren Kindern." )
    , ( "Deu 6:19", "dass er verjage alle deine Feinde vor dir, wie der HErr geredet hat." )
    , ( "Pro 24:3", "Durch Weisheit wird ein Haus gebaut und durch Verstand erhalten." )
    , ( "1Sa 17:29", "David antwortete: Was habe ich dir nun getan? Ist mir's nicht befohlen?" )
    , ( "Gen 24:64", "Und Rebekka hob ihre Augen auf und sah Isaak; da stieg sie eilend vom Kamel" )
    , ( "Psa 37:15", "Aber ihr Schwert wird in ihr Herz gehen, und ihr Bogen wird zerbrechen." )
    , ( "Lev 7:1", "Und dies ist das Gesetz des Schuldopfers. Ein Hochheiliges ist es." )
    , ( "Lam 5:1", "Gedenke, HErr, wie es uns geht; schaue und siehe an unsre Schmach!" )
    , ( "1Ki 5:24", "Also gab Hiram Salomo Zedern- und Tannenholz nach allem seinem Begehr." )
    , ( "1Co 15:16", "Denn so die Toten nicht auferstehen, so ist auch Christus nicht auferstanden." )
    , ( "Joh 12:36", "Glaubet an das Licht, dieweil ihr es habt, auf dass ihr des Lichtes Kinder seid." )
    , ( "2Sa 22:12", "Sein Gezelt um ihn her war finster und schwarze, dicke Wolken." )
    , ( "1Ch 4:36", "Eljoenai, Jaekoba, Jesohaja, Asaja, Adiel, Ismeel und Benaja," )
    , ( "Heb 7:10", "denn er war ja noch in den Lenden des Vaters, da ihm Melchisedek entgegenging." )
    , ( "Num 14:21", "Aber so wahr als ich lebe, so soll alle Herrlichkeit des HErrn voll werden." )
    , ( "Num 17:13", "und stand zwischen den Toten und den Lebendigen. Da ward der Plage gewehrt." )
    , ( "1Co 14:13", "Darum, welcher mit Zungen redet, der bete also, dass er's auch auslege." )
    , ( "Zec 6:2", "Am ersten Wagen waren rote Rosse, am andern Wagen waren schwarze Rosse," )
    , ( "Num 12:7", "Aber nicht also mein Knecht Mose, der in meinem ganzen Hause treu ist." )
    , ( "Mar 1:42", "Und als er so sprach, ging der Aussatz alsbald von ihm, und er ward rein." )
    , ( "Job 13:21", "lass deine Hand fern von mir sein, und dein Schrecken erschrecke mich nicht!" )
    , ( "Luk 10:28", "Er aber sprach zu ihm: Du hast recht geantwortet; tue das, so wirst du leben." )
    , ( "Mat 13:1", "An demselben Tage ging Jesus aus dem Hause und setzte sich an das Meer." )
    , ( "Joh 8:17", "Auch steht in eurem Gesetz geschrieben, dass zweier Menschen Zeugnis wahr sei." )
    , ( "Deu 25:12", "so sollst du ihr die Hand abhauen, und dein Auge soll sie nicht verschonen." )
    , ( "Job 22:9", "die Witwen hast du leer lassen gehen und die Arme der Waisen zerbrochen." )
    , ( "1Ch 1:7", "Die Kinder Javans sind: Elisa, Tharsisa, die Chittiter, die Dodaniter." )
    , ( "Psa 120:3", "Was kann dir die falsche Zunge tun, was kann sie ausrichten?" )
    , ( "Psa 119:40", "Siehe, ich begehre deiner Befehle; erquicke mich mit deiner Gerechtigkeit." )
    , ( "Psa 148:5", "Die sollen loben den Namen des HErrn; denn er gebot, da wurden sie geschaffen." )
    , ( "Joh 9:23", "Darum sprachen seine Eltern: er ist alt genug, fraget ihn selbst." )
    , ( "Exo 40:25", "und tat Lampen darauf vor dem HErrn, wie ihm der HErr geboten hatte," )
    , ( "Psa 105:17", "Er sandte einen Mann vor ihnen hin; Joseph ward zum Knecht verkauft." )
    , ( "Amo 8:1", "Der HERR zeigte mir ein Gesicht, und siehe, da stand ein Korb mit reifem Obst." )
    , ( "Luk 19:28", "Und als er solches sagte, zog er fort und reiste hinauf gen Jerusalem." )
    , ( "Psa 3:2", "Ach HErr, wie sind meiner Feinde so viel und setzen sich so viele wider mich!" )
    , ( "Psa 119:144", "Die Gerechtigkeit deiner Zeugnisse ist ewig; unterweise mich, so lebe ich." )
    , ( "1Ch 21:27", "Und der HErr sprach zum Engel, dass er sein Schwert in sein Scheide kehrte." )
    , ( "Isa 38:2", "Da wandte Hiskia sein Angesicht zur Wand und betete zum HErrn" )
    , ( "Psa 104:31", "Die Ehre des HErrn ist ewig; der HErr hat Wohlgefallen an seinen Werken." )
    , ( "1Ch 3:12", "des Sohn war Amazja; des Sohn war Asarja; des Sohn war Jotham;" )
    , ( "2Ch 8:1", "Und nach zwanzig Jahren, in welchen Salomo des HErrn Haus und sein Haus baute," )
    , ( "Eze 48:5", "Neben Manasse soll Ephraim seinen Teil haben, von Morgen bis gen Abend." )
    , ( "Psa 103:6", "Der HErr schafft Gerechtigkeit und Gericht allen, die Unrecht leiden." )
    , ( "Psa 118:22", "Der Stein, den die Bauleute verworfen haben, ist zum Eckstein geworden." )
    , ( "2Co 3:8", "wie sollte nicht viel mehr das Amt, das den Geist gibt, Klarheit haben!" )
    , ( "Psa 78:37", "aber ihr Herz war nicht fest an ihm, und hielten nicht treulich an seinem Bund." )
    , ( "Psa 22:21", "Errette meine Seele vom Schwert, meine einsame von den Hunden!" )
    , ( "Lev 9:16", "Und brachte das Brandopfer herzu und tat damit, wie es recht war." )
    , ( "Joh 6:6", "(Das sagte er aber, ihn zu versuchen; denn er wusste wohl, was er tun wollte.)" )
    , ( "1Co 9:6", "Oder haben allein ich und Barnabas keine Macht, nicht zu arbeiten?" )
    , ( "Psa 119:143", "Angst und Not haben mich getroffen; ich habe aber Lust an deinen Geboten." )
    , ( "2Ch 14:1", "Und Asa tat, was recht war und dem HErrn, seinem Gott, wohl gefiel," )
    , ( "1Ch 8:37", "Moza zeugte Binea; des Sohn war Rapha; des Sohn war Eleasa; des Sohn war Azel." )
    , ( "Lam 3:44", "Du hast dich mit einer Wolke verdeckt, dass kein Gebet hindurch konnte." )
    , ( "Exo 40:23", "und richtete Brot darauf zu vor dem HErrn, wie ihm der HErr geboten hatte," )
    , ( "1Ch 1:34", "Abraham zeugte Isaak. Die Kinder aber Isaaks sind: Esau und Israel." )
    , ( "Mar 5:10", "Und er bat ihn sehr, dass er sie nicht aus der Gegend triebe." )
    , ( "Phi 2:18", "Dessen sollt ihr euch auch freuen und sollt euch mit mir freuen." )
    , ( "Pro 17:17", "Ein Freund liebt allezeit, und als ein Bruder wird er in Not erfunden." )
    , ( "Job 20:14", "so wird seine Speise inwendig im Leibe sich verwandeln in Otterngalle." )
    , ( "Mat 1:8", "Asa zeugte Josaphat. Josaphat zeugte Joram. Joram zeugte Usia." )
    , ( "Joh 19:22", "Pilatus antwortete: Was ich geschrieben habe, das habe ich geschrieben." )
    , ( "Psa 115:10", "Das Haus Aaron hoffe auf den HErrn! Der ist ihre Hilfe und Schild." )
    , ( "Pro 14:13", "Auch beim Lachen kann das Herz trauern, und nach der Freude kommt Leid." )
    , ( "2Ki 4:32", "Und da Elisa ins Haus kam, siehe, da lag der Knabe tot auf seinem Bett." )
    , ( "Rev 2:6", "Aber das hast du, dass du die Werke der Nikolaiten hassest, welche ich auch hasse." )
    , ( "Jos 1:12", "Und zu den Rubenitern, Gaditern und dem halben Stamm Manasse sprach Josua:" )
    , ( "Num 33:24", "Vom Gebirge Sepher zogen sie aus und lagerten sich in Harada." )
    , ( "Psa 18:26", "Bei den Heiligen bist du heilig, und bei den Frommen bist du fromm," )
    , ( "Job 9:22", "Es ist eins, darum sage ich: Er bringt um beide, den Frommen und den Gottlosen." )
    , ( "Luk 23:13", "Pilatus aber rief die Hohenpriester und die Obersten und das Volk zusammen" )
    , ( "Job 39:9", "Meinst du das Einhorn werde dir dienen und werde bleiben an deiner Krippe?" )
    , ( "Psa 148:8", "Feuer, Hagel, Schnee und Dampf, Sturmwinde, die sein Wort ausrichten;" )
    , ( "Job 4:14", "da kam mich Furcht und Zittern an, und alle meine Gebeine erschraken." )
    , ( "Lev 18:22", "Du sollst nicht bei Knaben liegen wie beim Weibe; denn es ist ein Greuel." )
    , ( "1Ch 6:23", "des Sohnes Jizhars, des Sohnes Kahaths, des Sohnes Levis, des Sohnes Israels." )
    , ( "Ezr 10:28", "unter den Kindern Bebai: Johanan, Hananja, Sabbai und Athlai;" )
    , ( "Psa 51:12", "Schaffe in mir, Gott, ein reines Herz und gib mir einen neuen, gewissen Geist." )
    , ( "Gen 44:25", "Da sprach unser Vater: Ziehet wieder hin und kauft uns ein wenig Speise." )
    , ( "Exo 25:7", "Onyxsteine und eingefasste Steine zum Leibrock und zum Amtschild." )
    , ( "Deu 23:7", "Du sollst nicht ihren Frieden noch ihr Bestes suchen dein Leben lang ewiglich." )
    , ( "1Co 13:6", "sie freut sich nicht der Ungerechtigkeit, sie freut sich aber der Wahrheit;" )
    , ( "Psa 38:18", "Denn ich bin zu Leiden gemacht, und mein Schmerz ist immer vor mir." )
    , ( "Mar 3:25", "Und wenn ein Haus mit sich selbst uneins wird, kann es nicht bestehen." )
    , ( "Job 40:21", "Er liegt gern im Schatten, im Rohr und im Schlamm verborgen." )
    , ( "Num 14:1", "Da fuhr die ganze Gemeinde auf und schrie, und das Volk weinte die Nacht." )
    , ( "Joh 4:19", "Das Weib spricht zu ihm: Herr, ich sehe, dass du ein Prophet bist." )
    , ( "Psa 112:6", "Denn er wird ewiglich bleiben; des Gerechten wird nimmermehr vergessen." )
    , ( "Luk 2:19", "Maria aber behielt alle diese Worte und bewegte sie in ihrem Herzen." )
    , ( "Isa 60:8", "Wer sind die, welche fliegen wie die Wolken und wie die Tauben zu ihren Fenstern?" )
    , ( "2Ki 15:3", "Und er tat, was dem HErrn wohl gefiel, ganz wie sein Vater Amazja," )
    , ( "Ezr 2:36", "Der Priester: der Kinder Jedaja vom Hause Jesua neunhundert und dreiundsiebzig;" )
    , ( "Psa 107:38", "Und er segnete sie, dass sie sich sehr mehrten, und gab ihnen viel Vieh." )
    , ( "1Ch 23:8", "Die Kinder Laedans: der erste, Jehiel, Setham und Joel, die drei." )
    , ( "Psa 119:115", "Weichet von mir, ihr Boshaften! Ich will halten die Gebote meines Gottes." )
    , ( "Jos 10:43", "Und Josua zog wieder ins Lager gen Gilgal mit dem ganzen Israel." )
    , ( "Col 3:7", "in welchem auch ihr weiland gewandelt habt, da ihr darin lebtet." )
    , ( "Mar 3:12", "Und er bedrohte sie hart, dass sie ihn nicht offenbar machten." )
    , ( "Job 39:29", "Von dort schaut er nach der Speise, und seine Augen sehen ferne." )
    , ( "Joh 14:25", "Solches habe ich zu euch geredet, solange ich bei euch gewesen bin." )
    , ( "Pro 4:21", "Lass sie nicht von deinen Augen fahren, behalte sie in deinem Herzen." )
    , ( "Act 10:40", "Den hat Gott auferweckt am dritten Tage und ihn lassen offenbar werden," )
    , ( "Num 14:39", "Und Mose redete diese Worte zu allen Kindern Israel. Da trauerte das Volk sehr," )
    , ( "Psa 111:8", "Sie werden erhalten immer und ewiglich und geschehen treulich und redlich." )
    , ( "Pro 31:15", "Sie steht vor Tages auf und gibt Speise ihrem Hause und Essen ihren Dirnen." )
    , ( "Psa 78:41", "Sie versuchten Gott immer wieder und meisterten den Heiligen in Israel." )
    , ( "Lam 3:59", "Du siehest, HErr, wie mir so Unrecht geschieht; hilf mir zu meinem Recht!" )
    , ( "Isa 26:4", "Verlasset euch auf den HErrn ewiglich; denn Gott der HErr ist ein Fels ewiglich." )
    , ( "Act 5:1", "Ein Mann aber, mit Namen Ananias samt seinem Weibe Saphira verkaufte sein Gut" )
    , ( "Luk 4:15", "Und er lehrte in ihren Schulen und ward von jedermann gepriesen." )
    , ( "Psa 124:8", "Unsre Hilfe steht im Namen des HErrn, der Himmel und Erde gemacht hat." )
    , ( "Psa 89:31", "Wo aber seine Kinder mein Gesetz verlassen und in meinen Rechten nicht wandeln," )
    , ( "Job 28:24", "Denn er sieht die Enden der Erde und schaut alles, was unter dem Himmel ist." )
    , ( "Eze 3:16", "Und da die sieben Tage um waren, geschah des HErrn Wort zu mir und sprach:" )
    , ( "Eph 5:26", "auf dass er sie heiligte, und hat sie gereinigt durch das Wasserbad im Wort," )
    , ( "Phi 4:20", "Gott aber, unsrem Vater, sei Ehre von Ewigkeit zu Ewigkeit! Amen." )
    , ( "Job 37:17", "Du, des Kleider warm sind, wenn das Land still ist vom Mittagswinde," )
    , ( "Psa 106:24", "Und sie verachteten das liebe Land, sie glaubten seinem Wort nicht" )
    , ( "Psa 95:11", "dass ich schwur in meinem Zorn: Sie sollen nicht zu meiner Ruhe kommen." )
    , ( "Num 1:54", "Und die Kinder Israel taten alles, wie der HErr dem Mose geboten hatte." )
    , ( "Psa 139:22", "Ich hasse sie in rechtem Ernst; sie sind mir zu Feinden geworden." )
    , ( "2Sa 20:24", "Adoram war Rentmeister. Josaphat, der Sohn Ahiluds, war Kanzler." )
    , ( "Num 32:10", "Und des HErrn Zorn ergrimmte zur selben Zeit, und er schwur und sprach:" )
    , ( "Job 18:3", "Warum werden wir geachtet wie Vieh und sind so unrein vor euren Augen?" )
    , ( "Rut 4:8", "Und der Erbe sprach zu Boas: Kaufe du es! und zog seinen Schuh aus." )
    , ( "Mat 13:26", "Da nun das Kraut wuchs und Frucht brachte, da fand sich auch das Unkraut." )
    , ( "Exo 12:49", "Einerlei Gesetz sei dem Einheimischen und dem Fremdling, der unter euch wohnt." )
    , ( "Gen 5:20", "dass sein ganzes Alter ward neunhundertundzweiundsechzig Jahre, und starb." )
    , ( "Psa 119:99", "Ich bin gelehrter denn alle meine Lehrer; denn deine Zeugnisse sind meine Rede." )
    , ( "1Ch 4:25", "des Sohn war Sallum; des Sohn war Mibsam; des Sohn war Mismas." )
    , ( "2Sa 16:20", "Und Absalom sprach zu Ahithophel: Ratet zu, was sollen wir tun?" )
    , ( "2Th 2:5", "Gedenket ihr nicht daran, dass ich euch solches sagte, da ich noch bei euch war?" )
    , ( "Mic 2:5", "Jawohl, ihr werdet keinen Teil behalten in der Gemeinde des HErrn." )
    , ( "1Ch 7:26", "des Sohn war Laedan; des Sohn war Ammihud, des Sohn war Elisama" )
    , ( "Psa 6:4", "und meine Seele ist sehr erschrocken. Ach du, HErr, wie lange!" )
    , ( "Job 40:9", "Hast du einen Arm wie Gott, und kannst mit gleicher Stimme donnern, wie er tut?" )
    , ( "Job 38:30", "dass das Wasser verborgen wird wie unter Steinen und die Tiefe oben gefriert?" )
    , ( "Eze 48:4", "Neben Naphthali soll Manasse seinen Teil haben, von Morgen bis gen Abend." )
    , ( "Pro 4:19", "Der Gottlosen Weg aber ist wie Dunkel; sie wissen nicht, wo sie fallen werden." )
    , ( "Act 20:14", "Als er nun zu uns traf zu Assos, nahmen wir ihn zu uns und kamen gen Mitylene." )
    , ( "1Ch 1:38", "Die Kinder Seirs sind: Lotan, Sobal, Zibeon, Ana, Dison, Ezer, Disan." )
    , ( "Luk 14:20", "Und der dritte sprach: Ich habe ein Weib genommen, darum kann ich nicht kommen." )
    , ( "Mar 1:37", "Und da sie ihn fanden, sprachen sie zu ihm: Jedermann sucht dich." )
    , ( "Mat 18:5", "Und wer ein solches Kind aufnimmt in meinem Namen, der nimmt mich auf." )
    , ( "Deu 1:9", "Da sprach ich zu derselben Zeit zu euch: Ich kann nicht allein ertragen;" )
    , ( "1Ch 23:12", "Die Kinder Kahaths waren: Amram, Jizhar, Hebron und Usiel, die vier." )
    , ( "Psa 22:19", "Sie teilen meine Kleider unter sich und werfen das Los um mein Gewand." )
    , ( "Psa 83:6", "Denn sie haben sich miteinander vereinigt und einen Bund wider dich gemacht," )
    , ( "1Ch 18:12", "Und Abisai, der Zeruja Sohn, schlug der Edomiter im Salztal achtzehntausend" )
    , ( "Lam 3:52", "Meine Feinde haben mich gehetzt wie einen Vogel ohne Ursache;" )
    , ( "Isa 27:2", "Zu der Zeit wird man singen von dem Weinberge des besten Weins:" )
    , ( "Exo 25:15", "sie sollen in den Ringen bleiben und nicht herausgetan werden." )
    , ( "Phi 4:4", "Freuet euch in dem Herrn allewege! Und abermals sage ich: Freuet euch!" )
    , ( "1Ch 11:30", "Maherai, der Netophathiter; Heled, der Sohn Baanas, der Netophathiter;" )
    , ( "Amo 6:5", "und spielt auf dem Psalter und erdichtet euch Lieder wie David," )
    , ( "Isa 22:20", "Und zu der Zeit will ich rufen meinen Knecht Eljakim, den Sohn Hilkias," )
    , ( "1Co 14:17", "Du danksagest wohl fein, aber der andere wird nicht davon gebessert." )
    , ( "Psa 119:22", "Wende von mir Schmach und Verachtung; denn ich halte deine Zeugnisse." )
    ]


benignTextsGerman : List ( String, String )
benignTextsGerman =
    [ ( "", "random bla bla" )
    , ( "", "nonsense bla bla" )
    ]
