module Database exposing (..)

import String


type TextSource
    = God
    | RNN


type alias Document =
    { source : TextSource
    , passage : String
    , content : String
    }


trimLongerOne : List a -> List b -> ( List a, List b )
trimLongerOne xs ys =
    List.map2 (,) xs ys |> List.unzip


documentsEnglish : List Document
documentsEnglish =
    let
        allDivine =
            List.map (uncurry (Document God)) divineTextsEnglish

        allBenign =
            List.map (uncurry (Document RNN)) benignTextsEnglish

        ( divines, benigns ) =
            trimLongerOne allDivine allBenign
    in
        divines ++ benigns


documentsGerman : List Document
documentsGerman =
    let
        allDivine =
            List.map (uncurry (Document God)) divineTextsGerman

        allBenign =
            List.map (uncurry (Document RNN)) benignTextsGerman

        ( divines, benigns ) =
            trimLongerOne allDivine allBenign
    in
        divines ++ benigns


divineTextsEnglish : List ( String, String )
divineTextsEnglish =
    [ ( "Act 14:5", "And when they had preached the word in Perga, they went down into Attalia:" )
    , ( "Luk 18:3", "And when he heard this, he was very sorrowful: for he was very rich." )
    , ( "Job 4:6", "Is not this thy fear, thy confidence, thy hope, and the uprightness of thy ways?" )
    , ( "Act 28:4", "And some believed the things which were spoken, and some believed not." )
    , ( "Ezr 8:4", "Of the sons also of Bigvai; Uthai, and Zabbud, and with them seventy males." )
    , ( "Psa 119:3", "I will never forget thy precepts: for with them thou hast quickened me." )
    , ( "Jer 52:5", "So the city was besieged unto the eleventh year of king Zedekiah." )
    , ( "Ecc 4:9", "Two are better than one; because they have a good reward for their labour." )
    , ( "Psa 56:0", "In God will I praise his word: in the LORD will I praise his word." )
    , ( "Ch1 25:7", "The twentieth to Eliathah, he, his sons, and his brethren, were twelve:" )
    , ( "Pro 7:2", "Now is she without, now in the streets, and lieth in wait at every corner.)" )
    , ( "Psa 13:6", "I will sing unto the LORD, because he hath dealt bountifully with me." )
    , ( "Act 11:0", "And this was done three times: and all were drawn up again into heaven." )
    , ( "Pro 3:4", "Surely he scorneth the scorners: but he giveth grace unto the lowly." )
    , ( "Job 38:8", "When the dust groweth into hardness, and the clods cleave fast together?" )
    , ( "Mat 22:3", "He saith unto them, How then doth David in spirit call him Lord, saying," )
    , ( "Psa 60:5", "That thy beloved may be delivered; save with thy right hand, and hear me." )
    , ( "Heb 12:1", "And so terrible was the sight, that Moses said, I exceedingly fear and quake:)" )
    , ( "Psa 132:8", "Arise, O LORD, into thy rest; thou, and the ark of thy strength." )
    , ( "Pro 24:2", "For their calamity shall rise suddenly; and who knoweth the ruin of them both?" )
    , ( "Joh 9:6", "Then said they to him again, What did he to thee? how opened he thine eyes?" )
    , ( "Pro 13:7", "A wicked messenger falleth into mischief: but a faithful ambassador is health." )
    , ( "Job 20:3", "Though he spare it, and forsake it not; but keep it still within his mouth:" )
    , ( "Rom 15:2", "Let every one of us please his neighbour for his good to edification." )
    , ( "Mat 5:3", "Blessed are the poor in spirit: for theirs is the kingdom of heaven." )
    , ( "Pro 8:0", "I lead in the way of righteousness, in the midst of the paths of judgment:" )
    , ( "Gen 23:5", "And the children of Heth answered Abraham, saying unto him," )
    , ( "Exo 21:1", "Now these are the judgments which thou shalt set before them." )
    , ( "Mar 11:6", "And they said unto them even as Jesus had commanded: and they let them go." )
    , ( "Lam 5:4", "The elders have ceased from the gate, the young men from their musick." )
    , ( "Ti2 2:7", "Consider what I say; and the Lord give thee understanding in all things." )
    , ( "Ch1 26:4", "And Shebuel the son of Gershom, the son of Moses, was ruler of the treasures." )
    , ( "Mar 7:2", "And ye suffer him no more to do ought for his father or his mother;" )
    , ( "Pe1 1:9", "Receiving the end of your faith, even the salvation of your souls." )
    , ( "Rom 11:7", "For this is my covenant unto them, when I shall take away their sins." )
    , ( "Psa 119:6", "Great are thy tender mercies, O LORD: quicken me according to thy judgments." )
    , ( "Num 16:8", "And he stood between the dead and the living; and the plague was stayed." )
    , ( "Psa 123:1", "Unto thee lift I up mine eyes, O thou that dwellest in the heavens." )
    , ( "Job 9:8", "I am afraid of all my sorrows, I know that thou wilt not hold me innocent." )
    , ( "Luk 4:7", "And the fame of him went out into every place of the country round about." )
    , ( "Neh 7:4", "The children of Bazlith, the children of Mehida, the children of Harsha," )
    , ( "Col 3:9", " Husbands, love your wives, and be not bitter against them." )
    , ( "Gen 15:8", "And he said, LORD God, whereby shall I know that I shall inherit it?" )
    , ( "Mar 7:3", "All these evil things come from within, and defile the man." )
    , ( "Lev 16:5", "And the fat of the sin offering shall he burn upon the altar." )
    , ( "Heb 10:7", "For yet a little while, and he that shall come will come, and will not tarry." )
    , ( "Eze 7:5", "Thus saith the Lord GOD; An evil, an only evil, behold, is come." )
    , ( "Pro 18:9", "He also that is slothful in his work is brother to him that is a great waster." )
    , ( "Lev 11:1", "And the LORD spake unto Moses and to Aaron, saying unto them," )
    , ( "Job 30:7", "Among the bushes they brayed; under the nettles they were gathered together." )
    , ( "Exo 25:9", "Of a talent of pure gold shall he make it, with all these vessels." )
    , ( "Mat 14:6", "But Jesus said unto them, They need not depart; give ye them to eat." )
    , ( "Luk 2:2", "And Jesus increased in wisdom and stature, and in favour with God and man." )
    , ( "Lev 13:5", "But if the scall spread much in the skin after his cleansing;" )
    , ( "Psa 135:5", "For I know that the LORD is great, and that our Lord is above all gods." )
    , ( "Sol 7:1", "Come, my beloved, let us go forth into the field; let us lodge in the villages." )
    , ( "Pro 1:9", "For that they hated knowledge, and did not choose the fear of the LORD:" )
    , ( "Psa 51:2", "Restore unto me the joy of thy salvation; and uphold me with thy free spirit." )
    , ( "Job 22:9", "The righteous see it, and are glad: and the innocent laugh them to scorn." )
    , ( "Pro 14:9", "Fools make a mock at sin: but among the righteous there is favour." )
    , ( "Joh 10:4", "I am the good shepherd, and know my sheep, and am known of mine." )
    , ( "Psa 62:1", "Truly my soul waiteth upon God: from him cometh my salvation." )
    , ( "Gen 32:4", "Two hundred she goats, and twenty he goats, two hundred ewes, and twenty rams," )
    , ( "Ch2 9:8", "And they brought unto Solomon horses out of Egypt, and out of all lands." )
    , ( "Num 33:5", "And they departed from Ebronah, and encamped at Eziongaber." )
    , ( "Heb 11:8", "Of whom it was said, That in Isaac shall thy seed be called:" )
    , ( "Ch1 25:7", "The tenth to Shimei, he, his sons, and his brethren, were twelve:" )
    , ( "Isa 3:3", "The LORD standeth up to plead, and standeth to judge the people." )
    , ( "Gen 10:4", "And Pathrusim, and Casluhim, (out of whom came Philistim,) and Caphtorim." )
    , ( "Joh 6:8", "One of his disciples, Andrew, Simon Peter's brother, saith unto him," )
    , ( "Joh 2:2", "And both Jesus was called, and his disciples, to the marriage." )
    , ( "Ch1 12:6", "Elkanah, and Jesiah, and Azareel, and Joezer, and Jashobeam, the Korhites," )
    , ( "Gal 4:8", "Now we, brethren, as Isaac was, are the children of promise." )
    , ( "Jos 7:8", "O LORD, what shall I say, when Israel turneth their backs before their enemies!" )
    , ( "Gen 30:1", "And Leah said, A troop cometh: and she called his name Gad." )
    , ( "Act 26:5", "And I said, Who art thou, Lord? And he said, I am Jesus whom thou persecutest." )
    , ( "Zac 5:0", "Then said I to the angel that talked with me, Whither do these bear the ephah?" )
    , ( "Job 3:2", "Why did the knees prevent me? or why the breasts that I should suck?" )
    , ( "Rom 12:3", "Distributing to the necessity of saints; given to hospitality." )
    , ( "Mic 5:1", "And I will cut off the cities of thy land, and throw down all thy strong holds:" )
    , ( "Pro 10:4", "Wise men lay up knowledge: but the mouth of the foolish is near destruction." )
    , ( "Eph 6:4", "Grace be with all them that love our Lord Jesus Christ in sincerity. Amen." )
    , ( "Gen 38:0", "And the thing which he did displeased the LORD: wherefore he slew him also." )
    , ( "Ch1 24:2", "Of the Izharites; Shelomoth: of the sons of Shelomoth; Jahath." )
    , ( "Gen 49:2", "His eyes shall be red with wine, and his teeth white with milk." )
    , ( "Psa 47:8", "God reigneth over the heathen: God sitteth upon the throne of his holiness." )
    , ( "Psa 109:7", "That they may know that this is thy hand; that thou, LORD, hast done it." )
    , ( "Sol 1:9", "I have compared thee, O my love, to a company of horses in Pharaoh's chariots." )
    , ( "Plm 1:2", "Whom I have sent again: thou therefore receive him, that is, mine own bowels:" )
    , ( "Gen 30:3", "And she conceived, and bare a son; and said, God hath taken away my reproach:" )
    , ( "Col 3:4", " And above all these things put on charity, which is the bond of perfectness." )
    , ( "Num 19:1", "He that toucheth the dead body of any man shall be unclean seven days." )
    , ( "Mat 18:2", "And Jesus called a little child unto him, and set him in the midst of them," )
    , ( "Psa 69:5", "O God, thou knowest my foolishness; and my sins are not hid from thee." )
    , ( "Psa 31:5", "Into thine hand I commit my spirit: thou hast redeemed me, O LORD God of truth." )
    , ( "Joh 6:3", "And Jesus went up into a mountain, and there he sat with his disciples." )
    , ( "Luk 1:4", "And thou shalt have joy and gladness; and many shall rejoice at his birth." )
    , ( "Joh 1:0", "He was in the world, and the world was made by him, and the world knew him not." )
    , ( "Psa 136:1", "O give thanks unto the LORD; for he is good: for his mercy endureth for ever." )
    , ( "Kg2 6:7", "Therefore said he, Take it up to thee. And he put out his hand, and took it." )
    , ( "Kg2 25:2", "And the city was besieged unto the eleventh year of king Zedekiah." )
    , ( "Jo1 3:1", "Beloved, if our heart condemn us not, then have we confidence toward God." )
    , ( "Job 33:2", "Yea, his soul draweth near unto the grave, and his life to the destroyers." )
    , ( "Sol 6:7", "As a piece of a pomegranate are thy temples within thy locks." )
    , ( "Sa2 22:0", "He bowed the heavens also, and came down; and darkness was under his feet." )
    , ( "Psa 108:5", "Be thou exalted, O God, above the heavens: and thy glory above all the earth;" )
    , ( "Jon 2:0", "And the LORD spake unto the fish, and it vomited out Jonah upon the dry land." )
    , ( "Luk 13:3", "I tell you, Nay: but, except ye repent, ye shall all likewise perish." )
    , ( "Psa 115:6", "They have ears, but they hear not: noses have they, but they smell not:" )
    , ( "Psa 119:0", "Their heart is as fat as grease; but I delight in thy law." )
    , ( "Num 32:7", "And the children of Reuben built Heshbon, and Elealeh, and Kirjathaim," )
    , ( "Luk 13:9", "And if it bear fruit, well: and if not, then after that thou shalt cut it down." )
    , ( "Luk 1:5", "In holiness and righteousness before him, all the days of our life." )
    , ( "Jo3 1:3", "I had many things to write, but I will not with ink and pen write unto thee:" )
    , ( "Gen 49:0", "Out of Asher his bread shall be fat, and he shall yield royal dainties." )
    , ( "Mat 3:1", "In those days came John the Baptist, preaching in the wilderness of Judaea," )
    , ( "Sa2 14:1", "Now Joab the son of Zeruiah perceived that the king's heart was toward Absalom." )
    , ( "Psa 134:3", "The LORD that made heaven and earth bless thee out of Zion." )
    , ( "Joh 14:1", "Let not your heart be troubled: ye believe in God, believe also in me." )
    , ( "Ch1 2:7", "And Abigail bare Amasa: and the father of Amasa was Jether the Ishmeelite." )
    , ( "Num 7:8", "On the second day Nethaneel the son of Zuar, prince of Issachar, did offer:" )
    , ( "Psa 147:9", "He giveth to the beast his food, and to the young ravens which cry." )
    , ( "Th1 4:2", "For ye know what commandments we gave you by the Lord Jesus." )
    , ( "Psa 66:0", "Blessed be God, which hath not turned away my prayer, nor his mercy from me." )
    , ( "Neh 7:3", "The children of Bakbuk, the children of Hakupha, the children of Harhur," )
    , ( "Num 7:5", "One young bullock, one ram, one lamb of the first year, for a burnt offering:" )
    , ( "Rev 16:0", "And every island fled away, and the mountains were not found." )
    , ( "Jos 21:7", "Kedemoth with her suburbs, and Mephaath with her suburbs; four cities." )
    , ( "Pro 20:2", "The hearing ear, and the seeing eye, the LORD hath made even both of them." )
    , ( "Mar 5:1", "Now there was there nigh unto the mountains a great herd of swine feeding." )
    , ( "Sa1 6:1", "And the ark of the LORD was in the country of the Philistines seven months." )
    , ( "Num 7:1", "One young bullock, one ram, one lamb of the first year, for a burnt offering:" )
    , ( "Psa 89:3", "And I will beat down his foes before his face, and plague them that hate him." )
    , ( "Act 18:3", "Saying, This fellow persuadeth men to worship God contrary to the law." )
    , ( "Co1 11:9", "Neither was the man created for the woman; but the woman for the man." )
    , ( "Joh 15:3", "Now ye are clean through the word which I have spoken unto you." )
    , ( "Jer 13:2", "So I got a girdle according to the word of the LORD, and put it on my loins." )
    , ( "Exo 28:8", "And the second row shall be an emerald, a sapphire, and a diamond." )
    , ( "Jdg 17:1", "And there was a man of mount Ephraim, whose name was Micah." )
    , ( "Job 14:6", "For now thou numberest my steps: dost thou not watch over my sin?" )
    , ( "Mar 8:1", "And he said unto them, How is it that ye do not understand?" )
    , ( "Psa 106:3", "They soon forgat his works; they waited not for his counsel:" )
    , ( "Psa 83:8", "Assur also is joined with them: they have holpen the children of Lot. Selah." )
    , ( "Gal 6:2", "Bear ye one another's burdens, and so fulfil the law of Christ." )
    , ( "Mat 14:4", "And when they were gone over, they came into the land of Gennesaret." )
    , ( "Mat 11:4", "And if ye will receive it, this is Elias, which was for to come." )
    , ( "Gen 44:7", "And thy servant my father said unto us, Ye know that my wife bare me two sons:" )
    , ( "Joh 13:8", "Now no man at the table knew for what intent he spake this unto him." )
    , ( "Ch1 6:9", "And Aijalon with her suburbs, and Gathrimmon with her suburbs:" )
    , ( "Psa 145:9", "The LORD is good to all: and his tender mercies are over all his works." )
    , ( "Psa 110:7", "He shall drink of the brook in the way: therefore shall he lift up the head." )
    , ( "Phi 1:0", "Having the same conflict which ye saw in me, and now hear to be in me." )
    , ( "Ch1 1:9", "And the sons of Lotan; Hori, and Homam: and Timna was Lotan's sister." )
    , ( "Job 21:9", "Their houses are safe from fear, neither is the rod of God upon them." )
    , ( "Job 16:7", "Not for any injustice in mine hands: also my prayer is pure." )
    , ( "Gen 5:8", "And Lamech lived an hundred eighty and two years, and begat a son:" )
    , ( "Job 9:8", "He will not suffer me to take my breath, but filleth me with bitterness." )
    , ( "Job 7:7", "O remember that my life is wind: mine eye shall no more see good." )
    , ( "Heb 12:2", "Wherefore lift up the hands which hang down, and the feeble knees;" )
    , ( "Joh 14:8", "Philip saith unto him, Lord, shew us the Father, and it sufficeth us." )
    , ( "Kg1 4:2", "And these were the princes which he had; Azariah the son of Zadok the priest," )
    , ( "Tit 2:1", "For the grace of God that bringeth salvation hath appeared to all men," )
    , ( "Ch2 9:2", "And king Solomon passed all the kings of the earth in riches and wisdom." )
    , ( "Mat 14:7", "Whereupon he promised with an oath to give her whatsoever she would ask." )
    , ( "Deu 16:2", "Neither shalt thou set thee up any image; which the LORD thy God hateth." )
    , ( "Psa 106:8", "And a fire was kindled in their company; the flame burned up the wicked." )
    , ( "Pro 9:1", "Wisdom hath builded her house, she hath hewn out her seven pillars:" )
    , ( "Luk 23:2", "And there were also two other, malefactors, led with him to be put to death." )
    , ( "Co2 6:3", "Giving no offence in any thing, that the ministry be not blamed:" )
    , ( "Job 29:7", "And I brake the jaws of the wicked, and plucked the spoil out of his teeth." )
    , ( "Luk 20:8", "For he is not a God of the dead, but of the living: for all live unto him." )
    , ( "Eph 3:4", "Whereby, when ye read, ye may understand my knowledge in the mystery of Christ)" )
    , ( "Heb 3:1", "So I sware in my wrath, They shall not enter into my rest.)" )
    , ( "Psa 81:1", "Sing aloud unto God our strength: make a joyful noise unto the God of Jacob." )
    , ( "Deu 14:8", "And the stork, and the heron after her kind, and the lapwing, and the bat." )
    , ( "Pro 29:5", "A man that flattereth his neighbour spreadeth a net for his feet." )
    , ( "Lam 3:7", "He hath hedged me about, that I cannot get out: he hath made my chain heavy." )
    , ( "Pro 16:3", "Commit thy works unto the LORD, and thy thoughts shall be established." )
    , ( "Psa 139:3", "Search me, O God, and know my heart: try me, and know my thoughts:" )
    , ( "Luk 18:7", "And he said, The things which are impossible with men are possible with God." )
    , ( "Psa 35:5", "Let them be as chaff before the wind: and let the angel of the LORD chase them." )
    , ( "Act 6:0", "And they were not able to resist the wisdom and the spirit by which he spake." )
    , ( "Psa 78:1", "Yea, they turned back and tempted God, and limited the Holy One of Israel." )
    , ( "Eph 1:3", "Which is his body, the fulness of him that filleth all in all." )
    , ( "Pe1 3:1", "Let him eschew evil, and do good; let him seek peace, and ensue it." )
    , ( "Phi 3:7", "But what things were gain to me, those I counted loss for Christ." )
    , ( "Psa 84:9", "Behold, O God our shield, and look upon the face of thine anointed." )
    , ( "Psa 119:4", "Seven times a day do I praise thee because of thy righteous judgments." )
    , ( "Mat 14:4", "For John said unto him, It is not lawful for thee to have her." )
    , ( "Pro 2:8", "He keepeth the paths of judgment, and preserveth the way of his saints." )
    , ( "Rom 8:2", "Therefore, brethren, we are debtors, not to the flesh, to live after the flesh." )
    , ( "Num 3:4", "And the LORD spake unto Moses in the wilderness of Sinai, saying," )
    , ( "Jer 1:6", "Then said I, Ah, Lord GOD! behold, I cannot speak: for I am a child." )
    , ( "Ch2 28:6", "At that time did king Ahaz send unto the kings of Assyria to help him." )
    , ( "Sa2 24:9", "And David, according to the saying of Gad, went up as the LORD commanded." )
    , ( "Sol 4:5", "A fountain of gardens, a well of living waters, and streams from Lebanon." )
    , ( "Psa 3:3", "But thou, O LORD, art a shield for me; my glory, and the lifter up of mine head." )
    , ( "Ch1 2:9", "And when Azubah was dead, Caleb took unto him Ephrath, which bare him Hur." )
    , ( "Psa 33:1", "Rejoice in the LORD, O ye righteous: for praise is comely for the upright." )
    , ( "Psa 142:2", "I poured out my complaint before him; I shewed before him my trouble." )
    , ( "Co2 1:2", "Who hath also sealed us, and given the earnest of the Spirit in our hearts." )
    , ( "Mar 4:8", "And these are they which are sown among thorns; such as hear the word," )
    , ( "Job 9:7", "Which commandeth the sun, and it riseth not; and sealeth up the stars." )
    , ( "Gen 42:2", "And he said unto them, Nay, but to see the nakedness of the land ye are come." )
    , ( "Psa 103:8", "The LORD is merciful and gracious, slow to anger, and plenteous in mercy." )
    , ( "Joh 12:1", "These things said Esaias, when he saw his glory, and spake of him." )
    , ( "Psa 9:7", "But the LORD shall endure for ever: he hath prepared his throne for judgment." )
    , ( "Pro 6:3", "A wound and dishonour shall he get; and his reproach shall not be wiped away." )
    , ( "Joh 6:0", "Jesus answered them, Have not I chosen you twelve, and one of you is a devil?" )
    , ( "Mat 20:5", "Again he went out about the sixth and ninth hour, and did likewise." )
    , ( "Job 37:9", "Out of the south cometh the whirlwind: and cold out of the north." )
    , ( "Luk 14:2", "And, behold, there was a certain man before him which had the dropsy." )
    , ( "Exo 25:6", "And thou shalt put into the ark the testimony which I shall give thee." )
    , ( "Rut 4:8", "Therefore the kinsman said unto Boaz, Buy it for thee. So he drew off his shoe." )
    , ( "Isa 12:3", "Therefore with joy shall ye draw water out of the wells of salvation." )
    , ( "Pro 2:3", "Who leave the paths of uprightness, to walk in the ways of darkness;" )
    , ( "Act 19:8", "And many that believed came, and confessed, and shewed their deeds." )
    , ( "Exo 29:5", "And I will dwell among the children of Israel, and will be their God." )
    , ( "Joh 15:2", "This is my commandment, That ye love one another, as I have loved you." )
    , ( "Psa 51:9", "Hide thy face from my sins, and blot out all mine iniquities." )
    , ( "Jam 2:2", "So speak ye, and so do, as they that shall be judged by the law of liberty." )
    , ( "Psa 119:4", "Thou art my hiding place and my shield: I hope in thy word." )
    , ( "Th1 4:7", "For God hath not called us unto uncleanness, but unto holiness." )
    , ( "Exo 26:2", "And for the sides of the tabernacle westward thou shalt make six boards." )
    , ( "Exo 36:7", "And for the sides of the tabernacle westward he made six boards." )
    , ( "Psa 97:6", "The heavens declare his righteousness, and all the people see his glory." )
    , ( "Ezr 2:2", "The children of Bazluth, the children of Mehida, the children of Harsha," )
    , ( "Gen 36:4", "And Jobab died, and Husham of the land of Temani reigned in his stead." )
    , ( "Ch1 24:7", "The one and twentieth to Jachin, the two and twentieth to Gamul," )
    , ( "Luk 21:2", "And he saw also a certain poor widow casting in thither two mites." )
    , ( "Psa 3:2", "Many there be which say of my soul, There is no help for him in God. Selah." )
    , ( "Mat 15:0", "And he called the multitude, and said unto them, Hear, and understand:" )
    , ( "Job 36:6", "He preserveth not the life of the wicked: but giveth right to the poor." )
    , ( "Isa 43:8", "Bring forth the blind people that have eyes, and the deaf that have ears." )
    , ( "Jer 14:1", "Then said the LORD unto me, Pray not for this people for their good." )
    , ( "Gen 9:9", "And all the days of Noah were nine hundred and fifty years: and he died." )
    , ( "Phi 2:0", "For I have no man likeminded, who will naturally care for your state." )
    , ( "Gen 7:5", "And Noah did according unto all that the LORD commanded him." )
    , ( "Jon 1:1", "Now the word of the LORD came unto Jonah the son of Amittai, saying," )
    , ( "Luk 12:4", "Of a truth I say unto you, that he will make him ruler over all that he hath." )
    , ( "Jer 38:1", "But if thou refuse to go forth, this is the word that the LORD hath shewed me:" )
    , ( "Psa 116:2", "What shall I render unto the LORD for all his benefits toward me?" )
    , ( "Jam 1:3", "Knowing this, that the trying of your faith worketh patience." )
    , ( "Psa 22:9", "But be not thou far from me, O LORD: O my strength, haste thee to help me." )
    , ( "Rom 6:0", "For when ye were the servants of sin, ye were free from righteousness." )
    , ( "Hos 10:7", "As for Samaria, her king is cut off as the foam upon the water." )
    , ( "Ch1 6:7", "And these be the names of the sons of Gershom; Libni, and Shimei." )
    , ( "Pro 23:4", "Thou shalt beat him with the rod, and shalt deliver his soul from hell." )
    , ( "Psa 76:9", "When God arose to judgment, to save all the meek of the earth. Selah." )
    , ( "Deu 19:7", "Wherefore I command thee, saying, Thou shalt separate three cities for thee." )
    , ( "Hos 13:5", "I did know thee in the wilderness, in the land of great drought." )
    , ( "Act 23:6", "Claudius Lysias unto the most excellent governor Felix sendeth greeting." )
    , ( "Job 6:8", "Now therefore be content, look upon me; for it is evident unto you if I lie." )
    , ( "Mar 10:0", "And he, casting away his garment, rose, and came to Jesus." )
    , ( "Gen 32:7", "And he said unto him, What is thy name? And he said, Jacob." )
    , ( "Pro 22:4", "By humility and the fear of the LORD are riches, and honour, and life." )
    , ( "Th1 1:7", "So that ye were ensamples to all that believe in Macedonia and Achaia." )
    , ( "Luk 14:0", "Saying, This man began to build, and was not able to finish." )
    , ( "Job 34:4", "Let men of understanding tell me, and let a wise man hearken unto me." )
    , ( "Phi 3:1", "If by any means I might attain unto the resurrection of the dead." )
    , ( "Jos 12:9", "The king of Jericho, one; the king of Ai, which is beside Bethel, one;" )
    , ( "Luk 1:0", "And his mercy is on them that fear him from generation to generation." )
    , ( "Psa 92:5", "O LORD, how great are thy works! and thy thoughts are very deep." )
    , ( "Neh 11:6", "And of the Levites were divisions in Judah, and in Benjamin." )
    , ( "Joh 11:8", "Now Bethany was nigh unto Jerusalem, about fifteen furlongs off:" )
    , ( "Psa 89:3", "I have made a covenant with my chosen, I have sworn unto David my servant," )
    , ( "Neh 11:8", "All the Levites in the holy city were two hundred fourscore and four." )
    , ( "Pe1 3:3", "And who is he that will harm you, if ye be followers of that which is good?" )
    , ( "Gen 2:5", "And they were both naked, the man and his wife, and were not ashamed." )
    , ( "Psa 73:1", "Truly God is good to Israel, even to such as are of a clean heart." )
    , ( "Num 22:9", "And Balaam went with Balak, and they came unto Kirjathhuzoth." )
    , ( "Mat 15:5", "Then answered Peter and said unto him, Declare unto us this parable." )
    , ( "Psa 119:3", "Teach me, O LORD, the way of thy statutes; and I shall keep it unto the end." )
    , ( "Sa1 19:2", "So Michal let David down through a window: and he went, and fled, and escaped." )
    , ( "Kg1 13:7", "And he spake to his sons, saying, Saddle me the ass. And they saddled him." )
    , ( "Mat 23:6", "And love the uppermost rooms at feasts, and the chief seats in the synagogues," )
    , ( "Hag 1:3", "Then came the word of the LORD by Haggai the prophet, saying," )
    , ( "Sol 2:5", "Stay me with flagons, comfort me with apples: for I am sick of love." )
    , ( "Joh 5:7", "But Jesus answered them, My Father worketh hitherto, and I work." )
    , ( "Psa 37:3", "The LORD shall laugh at him: for he seeth that his day is coming." )
    , ( "Gen 13:3", "But the men of Sodom were wicked and sinners before the LORD exceedingly." )
    , ( "Job 8:1", "Can the rush grow up without mire? can the flag grow without water?" )
    , ( "Psa 107:9", "For he satisfieth the longing soul, and filleth the hungry soul with goodness." )
    , ( "Luk 24:1", "And their words seemed to them as idle tales, and they believed them not." )
    , ( "Job 41:2", "In his neck remaineth strength, and sorrow is turned into joy before him." )
    , ( "Mat 4:1", "Then the devil leaveth him, and, behold, angels came and ministered unto him." )
    , ( "Gen 5:1", "And Enoch lived sixty and five years, and begat Methuselah:" )
    , ( "Psa 119:4", "Deliver me from the oppression of man: so will I keep thy precepts." )
    , ( "Psa 105:5", "He turned their heart to hate his people, to deal subtilly with his servants." )
    , ( "Joh 12:0", "But the chief priests consulted that they might put Lazarus also to death;" )
    , ( "Job 13:3", "Surely I would speak to the Almighty, and I desire to reason with God." )
    , ( "Lev 24:4", "He shall order the lamps upon the pure candlestick before the LORD continually." )
    , ( "Pro 11:4", "Riches profit not in the day of wrath: but righteousness delivereth from death." )
    , ( "Psa 72:2", "He shall judge thy people with righteousness, and thy poor with judgment." )
    , ( "Mat 25:1", "Afterward came also the other virgins, saying, Lord, Lord, open to us." )
    , ( "Ch1 25:1", "The fourth to Izri, he, his sons, and his brethren, were twelve:" )
    , ( "Rom 12:7", "Or ministry, let us wait on our ministering: or he that teacheth, on teaching;" )
    , ( "Jer 13:3", "And the word of the LORD came unto me the second time, saying," )
    , ( "Pro 31:1", "The words of king Lemuel, the prophecy that his mother taught him." )
    , ( "Lev 26:7", "And ye shall chase your enemies, and they shall fall before you by the sword." )
    , ( "Psa 105:7", "They shewed his signs among them, and wonders in the land of Ham." )
    , ( "Mat 15:1", "Then Jesus went thence, and departed into the coasts of Tyre and Sidon." )
    , ( "Lam 3:3", "He hath caused the arrows of his quiver to enter into my reins." )
    , ( "Ch1 26:3", "Of the Amramites, and the Izharites, the Hebronites, and the Uzzielites:" )
    , ( "Ch1 9:0", "And the son of Jonathan was Meribbaal: and Meribbaal begat Micah." )
    , ( "Psa 90:7", "For we are consumed by thine anger, and by thy wrath are we troubled." )
    , ( "Mat 14:5", "And in the fourth watch of the night Jesus went unto them, walking on the sea." )
    , ( "Ecc 2:4", "I made me great works; I builded me houses; I planted me vineyards:" )
    , ( "Psa 26:6", "I will wash mine hands in innocency: so will I compass thine altar, O LORD:" )
    , ( "Tit 3:6", "Which he shed on us abundantly through Jesus Christ our Saviour;" )
    , ( "Pro 29:1", "A fool uttereth all his mind: but a wise man keepeth it in till afterwards." )
    , ( "Ecc 7:9", "Wisdom strengtheneth the wise more than ten mighty men which are in the city." )
    , ( "Pro 8:3", "I was set up from everlasting, from the beginning, or ever the earth was." )
    , ( "Ezr 2:5", "The children of Senaah, three thousand and six hundred and thirty." )
    , ( "Mat 26:6", "Now when Jesus was in Bethany, in the house of Simon the leper," )
    , ( "Ch1 7:1", "Now the sons of Issachar were, Tola, and Puah, Jashub, and Shimrom, four." )
    , ( "Deu 6:6", "And these words, which I command thee this day, shall be in thine heart:" )
    , ( "Job 3:8", "There the prisoners rest together; they hear not the voice of the oppressor." )
    , ( "Gal 3:4", "Have ye suffered so many things in vain? if it be yet in vain." )
    , ( "Num 28:9", "A several tenth deal unto one lamb, throughout the seven lambs;" )
    , ( "Eze 48:9", "And they that serve the city shall serve it out of all the tribes of Israel." )
    , ( "Gen 4:3", "And Cain said unto the LORD, My punishment is greater than I can bear." )
    , ( "Psa 29:1", "Give unto the LORD, O ye mighty, give unto the LORD glory and strength." )
    , ( "Num 23:5", "And Balak said unto Balaam, Neither curse them at all, nor bless them at all." )
    , ( "Jer 13:5", "So I went, and hid it by Euphrates, as the LORD commanded me." )
    , ( "Psa 148:8", "Fire, and hail; snow, and vapours; stormy wind fulfilling his word:" )
    , ( "Pro 30:2", "Surely I am more brutish than any man, and have not the understanding of a man." )
    , ( "Luk 23:4", "And that day was the preparation, and the sabbath drew on." )
    , ( "Psa 119:2", "Mine eyes fail for thy word, saying, When wilt thou comfort me?" )
    , ( "Gen 10:8", "And Cush begat Nimrod: he began to be a mighty one in the earth." )
    , ( "Mat 13:7", "And some fell among thorns; and the thorns sprung up, and choked them:" )
    , ( "Job 28:8", "The lion's whelps have not trodden it, nor the fierce lion passed by it." )
    , ( "Psa 119:7", "I am afflicted very much: quicken me, O LORD, according unto thy word." )
    ]


benignTextsEnglish : List ( String, String )
benignTextsEnglish =
    [ ( "ᛯ", "And they shall be his wife, and of multitude of a priest's meat offering." )
    , ( "ᛯ", "The righteous shall come thou with Jerusalem: and I will receiveth the south work." )
    , ( "ᛯ", "Sing the LORD shall not deter of people, as he knoweth devise." )
    , ( "ᛯ", "Then these company of his stain were in the will over thee, that I am before." )
    , ( "ᛯ", "For my lord thou, under the law, O LORD; now who is he forgiven." )
    , ( "ᛯ", "Then talk the beall is evil of the sons of Baashan, the wine was on their enemies." )
    , ( "ᛯ", "And as above thee which shall be of the commandments of an atonement and strength." )
    , ( "ᛯ", "Evites in meat offering made she had known of trescausteth her souls." )
    , ( "ᛯ", "And Esau do it to be spear into the eyes, and satisfy according to the LORD." )
    , ( "ᛯ", "And Isaiah David and Ahabmaz his God conceived as for their discribes, saying," )
    , ( "ᛯ", "And the Gent thine enemy was a wife, and have seen at the two land:" )
    , ( "ᛯ", "Thine harmighteth with the two sons by the glory of the LORD a man before these." )
    , ( "ᛯ", "Neither drosper he recontwered a liher from the land of Judah flee." )
    , ( "ᛯ", "And Hy sepord his what could not likened herb back, and there came to posts." )
    , ( "ᛯ", "And David had laid upon him a little stirrons, and sow perfected." )
    , ( "ᛯ", "Then rise for the LORD, even him the host, and those that pass thereon thereof." )
    , ( "ᛯ", "Thou is sealented witness, and said unto them, Take his word after Esaiah Joab;" )
    , ( "ᛯ", "And the sinnified with us; it be not continually, and I will hear no possession." )
    , ( "ᛯ", "Seven hand be not hid Ethaniah, the Philistines shall that turn born incense." )
    , ( "ᛯ", "Sared their camesbinds, and our extell and fought unto the word?" )
    , ( "ᛯ", "Believes began down, and his flocks. Because ye make Maishan and Jacob." )
    , ( "ᛯ", "They shall not born every one that hear was in it, and shalt kill thee?" )
    , ( "ᛯ", "Therefore when I smocted her offering have nom for they were not." )
    , ( "ᛯ", "The ones of thy house thereof with bedient, lfounds at David's souls." )
    , ( "ᛯ", "And Moses said unto them, Re thou brought over them out of your nolish money." )
    , ( "ᛯ", "Ye shall be to war, said unto me, Thus saith the Lord GOD into a weeping." )
    , ( "ᛯ", "O Go into the well, did eat, and give, on the mount of thy words." )
    , ( "ᛯ", "Then they spake unto thescomed from the sabbath, and the young men that lieth as." )
    , ( "ᛯ", "Beholdver with thee betwien half his rices of Israel, did Syria carcceeth?" )
    , ( "ᛯ", "Minacle province them lips without: but the Syriats is to turn break one kings." )
    , ( "ᛯ", "And it shall not thine heart upon honour, and except and the famine flesh." )
    , ( "ᛯ", "All ye west to heam delivered himself, and is time to incense toward the land." )
    , ( "ᛯ", "Those that spoilesteth in Israel, which they have lifts in the way of his house." )
    , ( "ᛯ", "And if ye the fire of every speakants, and called not for a put away the city." )
    , ( "ᛯ", "All that are my peoples like, because the face, which be mount Hezekiah." )
    , ( "ᛯ", "But the Heture be a fair are cometh: a word weph coupleth over a great hundred:" )
    , ( "ᛯ", "The nations shall provoketh the arches, even of a pray throughout." )
    , ( "ᛯ", "The LORD five beloved and perpetures, posge over all the captivity!" )
    , ( "ᛯ", "And when he said, give his daughter ye shall surely poor to bless it." )
    , ( "ᛯ", "And the testimony of the bread of Zibalmer before Jerusalem, saying," )
    , ( "ᛯ", "But the LORD God of Israel had seen after money, my soul is gonds:" )
    , ( "ᛯ", "And what thy whole wealt wilt they doth brass shall not destroy it." )
    , ( "ᛯ", "Then say in the hundred blood: become in passueds; they should not be gathered?" )
    , ( "ᛯ", "And the knowledte because of all that asher thou mayest breaketh by a water." )
    , ( "ᛯ", "The dead? And the Almightily the wondekin Isaac decrain the LORD is glorious," )
    , ( "ᛯ", "And thee man that the remnant of the LORD in the holy hand from sinnerning." )
    , ( "ᛯ", "And Abraham according to all the cleans the inward, to speak for your north." )
    , ( "ᛯ", "This is an end, nor rolleth? which ye pour thine ear unto Arduel." )
    , ( "ᛯ", "And Samosh speaketh none ear, and a time, that Gidnebah, in the children of Egypt?" )
    , ( "ᛯ", "Neither shall they had set night in all the burnt offering unto our days to day." )
    , ( "ᛯ", "Son of man answered; and Zoab the man shall envants, as ye was called Kish." )
    , ( "ᛯ", "And the Chaldeans under a ramber of Egypt, and shall walk shall it five compant." )
    , ( "ᛯ", "Lo, be turned the figs of Israel, which ye were broken me a month aproin;" )
    , ( "ᛯ", "Ye shouldest men dark and barketh with the stones of my brethren." )
    , ( "ᛯ", "For all who not a children upon mount Shiloh's servant, and I will cace oil." )
    , ( "ᛯ", "According in the wilderness, and her name rained break upon our vanners." )
    , ( "ᛯ", "And Hashi, Mapher, and Nehuiah, and Isaac, and Joash begat Aaron," )
    , ( "ᛯ", "The LORD have daughters the weight of Epervai sinter and grape, I earth with him." )
    , ( "ᛯ", "For thou shalt lie in for a sore come to do that were two evil?" )
    , ( "ᛯ", "And Moses yet shall be hot the heaven: to war, spake unto you." )
    , ( "ᛯ", "He shall rebel: yet strength of bysw was of my truth and sent come upon a bald." )
    , ( "ᛯ", "There was executed my father: thou shalt take war a man of niters:" )
    , ( "ᛯ", "And Abishaz were one of the land of Michabeah took to Hazarger." )
    , ( "ᛯ", "And now Dobour came out the trions of thy wine, band two before him." )
    , ( "ᛯ", "But he cast out thee upon his commance of beasts and fruit thereon." )
    , ( "ᛯ", "Hear, and the Levites shall give awake of the burdueding four tribitation." )
    , ( "ᛯ", "Thy servants which cainth evil that also will be thou to Redeuzar, and was gift." )
    , ( "ᛯ", "And Ahab was it is good; in the land is Esthan, and Janag, and Uz." )
    , ( "ᛯ", "And the LORD sisten the bill the princes, which had a knowledgeless images." )
    , ( "ᛯ", "Which said, He nation which the LORD had brought it a coveption commandment?" )
    , ( "ᛯ", "My father is thy mightmors revoures, he that didst off his God of their flocks." )
    , ( "ᛯ", "For it is upon the house of Israel, that it might bless for any judgment." )
    , ( "ᛯ", "The feel therefore it change against Betheth given man's house;" )
    , ( "ᛯ", "Then the servants was yet a covenant Jerusalem yare, and layeth me." )
    , ( "ᛯ", "Who hath hearkened, saying, Which have ye knoweth thy days hath he my God ashamed." )
    , ( "ᛯ", "And the time thereof shall come above them of them; his sons, to, O hundred men." )
    , ( "ᛯ", "And he said, Let all that at the verysomory which Jabess they seed uptill his arm." )
    , ( "ᛯ", "For the LORD hath no plaeseth reparted, ill his father did the droth." )
    , ( "ᛯ", "Thinking it vain and a sweet, was now in mule, at that brind, and hasts in law." )
    , ( "ᛯ", "Then worship thy father or one, two night; they hath not depart, and asked me it." )
    , ( "ᛯ", "Morably I said, What quenches to whom ye have sending together in judged." )
    , ( "ᛯ", "That he departed up before them, were as thou hadst understand me." )
    , ( "ᛯ", "The mouth that we may also to hearted for others of fine mother:" )
    , ( "ᛯ", "And their God began the hurbign ye shall be in the glory of the commandment." )
    , ( "ᛯ", "So return shall therefore kand; saying, What one gone nor parts." )
    , ( "ᛯ", "They are borsge ordering also of death to see, to speak with by wicked chariots," )
    , ( "ᛯ", "And they are made of terror thing underthards: and they sanctified in." )
    , ( "ᛯ", "And the daughter in the jubile that cast ye ten deter of the head." )
    , ( "ᛯ", "Wherefore there was many with their cold, then he have I be abupher." )
    , ( "ᛯ", "Behold, I will continual unto me, I swear before thee, and put thee oil to war." )
    , ( "ᛯ", "And they be the bean of the lad drink out, and weth, from his mouth was iniquity:" )
    , ( "ᛯ", "And all the prey of the Egyptian, and a with gold off what is not because." )
    , ( "ᛯ", "Hear the Philistines have I shall dwell like Moabhaniah, saying," )
    , ( "ᛯ", "And Adar's right years had assed agone, to over my suctiful on you not." )
    , ( "ᛯ", "But do and reigned because of the city, and company, and return before the LORD." )
    , ( "ᛯ", "The covenant of oil, and made her twater, he was upon their evil tay?" )
    , ( "ᛯ", "When thou hast shall sureled clouds in the inhabitants of Jerobam.)" )
    , ( "ᛯ", "At this nations in his life: for I have promised them was slain." )
    , ( "ᛯ", "And, because thou turned with Carner, saith the LORD of hosts." )
    , ( "ᛯ", "And it shall speak with the vamelites of those which he laid up from Solomon." )
    , ( "ᛯ", "And Ophir, twenty years of his foot, O ye also in Jerusalem with his fifties." )
    , ( "ᛯ", "When I shall flee the LORD this anointing two manner comentage in thee." )
    , ( "ᛯ", "And thou, lox the word of Ephraim, touch among them as a rulers." )
    , ( "ᛯ", "And David spoken by me: for thou art gone it unto a tree mine a mercy." )
    , ( "ᛯ", "And his day of the land in all the garrisons, they said unto them:" )
    , ( "ᛯ", "Sleeded Samuel and Hodah: so declare them; therefore there was Niph." )
    , ( "ᛯ", "And he shall come upon that stretched out, the semperiting in the city of Daisah." )
    , ( "ᛯ", "The Shiloth had in his archer together, as they have smitten unto this day." )
    , ( "ᛯ", "And it came to pass, that I went up his live, ye life which is with the womb?" )
    , ( "ᛯ", "And it that he commanded thee, and did when the sword were brass;" )
    , ( "ᛯ", "Cide forty all their voice and herbs of that pleasure, and what is their wind." )
    , ( "ᛯ", "But David brought the divers come upon you, sour that is both to Cain." )
    , ( "ᛯ", "And grapes thy great men of God and all the princes of the hands of the mouth," )
    , ( "ᛯ", "Hearken the king rent for also back, the elders of the LORD's wicked him." )
    , ( "ᛯ", "And he passed out of Jerusalem, saying, Ageisfif thou those is delicto." )
    , ( "ᛯ", "And the money therefore the men of Cunnelves with the camp; depart them." )
    , ( "ᛯ", "Behold, thou shalt sell at my clothes, and slew; and go up expies:" )
    , ( "ᛯ", "Thou hast breach what I say, We lointly her way, to go in their villages." )
    , ( "ᛯ", "So there is thy strength: hast the tail out of the midst daily his hungred." )
    , ( "ᛯ", "Even was spoken of the sabbath nations, the Jews of Issachar, and Rehoboab," )
    , ( "ᛯ", "And the thou cleast Gid like throne: that they be afore thou former unto the LORD." )
    , ( "ᛯ", "And I will pass down, and the band of the king of Egypt; in the land of Judah." )
    , ( "ᛯ", "And he saw that the LORD thy God, according to all this day to come to his." )
    , ( "ᛯ", "And the third may feed the little of the flome of the plain, and bare." )
    , ( "ᛯ", "Wo her sin; that it shall be silver, and cover themen unto me, Markish," )
    , ( "ᛯ", "The children of Jabethan shall be unto Cammi, he did unto her, saying," )
    , ( "ᛯ", "Look now, he one wine? And when could not be young fool of the lightness." )
    , ( "ᛯ", "And David cannot be, my father's days which have yess desolate;" )
    , ( "ᛯ", "Samb kept, Coun beams thereof by the house of the gate; and the house of the LORD." )
    , ( "ᛯ", "And, behold, I saw that by the heart over the land that I did so Israel consumed." )
    , ( "ᛯ", "Beast pure in the wicked, and shall surely men of great eyes' wisdom." )
    , ( "ᛯ", "Nevertheless any that I may make an strong before the unclean." )
    , ( "ᛯ", "And the bowls are touche, they rested, and teverath, and corvertaw," )
    , ( "ᛯ", "Behold, I pray you through can for thine enemies, and sealeth, and cast out." )
    , ( "ᛯ", "And they strive unto their daughter of mine own hundred, and ephah and Horam.)" )
    , ( "ᛯ", "And Joshua might I providing as it fer, an heave moved these houses." )
    , ( "ᛯ", "And Magone, drink together, and warned with you out to rejoylu." )
    , ( "ᛯ", "Who hath not made a day concerning the river, and I will be things are broken:" )
    , ( "ᛯ", "Reipiseth thyself in his honination, and know them he that be burnt one." )
    , ( "ᛯ", "What thou cut down upon the fear of the horns of my might off." )
    , ( "ᛯ", "This were not the LORD will carry, and that no masters of his host of the land;" )
    , ( "ᛯ", "And the king said, My men ye save their families; shall slew thy bread an overt." )
    , ( "ᛯ", "Therefore believe him such ases, that he might hath despised my hand." )
    , ( "ᛯ", "By loved ye have brought into the camp, according to the sword from Jerusalem:" )
    , ( "ᛯ", "Therefore ye delight seen sick to his father, and washed, saying," )
    , ( "ᛯ", "And it was they that layes' servants, and I will fall, and rose up." )
    , ( "ᛯ", "According mine hand was not his cloud for Aaron, and they of the LORD's." )
    , ( "ᛯ", "And, in the two son of my beloved against the Philistine great there." )
    , ( "ᛯ", "But Nethaliah the Jegholdan to Aaron Hilkiah, who went to morrow," )
    , ( "ᛯ", "Thou leave he made poortions, even on. All trock thy truely with it." )
    , ( "ᛯ", "Gos of their present house for his house, when thou killeths he." )
    , ( "ᛯ", "And I shall come their called by his line name, the Issaipon, profore you:" )
    , ( "ᛯ", "They made of his forest hast thou be unclean upon their ear, shall lot thyself," )
    , ( "ᛯ", "Then the Ammonites, the rempains, and Jehosowepss, yea, as ye be left this bow;" )
    , ( "ᛯ", "And Uz, and he will bring darkness awaken with them counteth good." )
    , ( "ᛯ", "So Sidon to me for your generations; and lothe humble the multity to Allstob," )
    , ( "ᛯ", "And Iram am, forting and bare but not, nor wise any of this dost?" )
    , ( "ᛯ", "And what the breadth of Israel were told you, which he departed." )
    , ( "ᛯ", "Selah said, Now it gatherness, because grant in all justion, as is men;" )
    , ( "ᛯ", "And if the king said unto him, Taboah in the cart that I forward." )
    , ( "ᛯ", "And they rage upon us in thy grajor, because the flocks of many word to do?" )
    , ( "ᛯ", "Judge to angel went forth would according to the land of Israel." )
    , ( "ᛯ", "And as a spook in Zion, goeth, and an instrunt, and sacrificed upon me." )
    , ( "ᛯ", "Now he reigned out of his heart in people tree, O six wround about's offering?" )
    , ( "ᛯ", "Therefore it laid Ephraim; the medbearing of The threesting first chiependy." )
    , ( "ᛯ", "And over the other mone of ward, and remembered from the house." )
    , ( "ᛯ", "The foundation of the head of the LORD, and have no master therein." )
    , ( "ᛯ", "And said, The LORD shall rend past him, when he may deliver these more." )
    , ( "ᛯ", "Surely be drink of their fathers of Hawar, and Jadak, and Eli." )
    , ( "ᛯ", "But we be brought you? and all a piller that slew he abide unto thee." )
    , ( "ᛯ", "And from the Cambuchathor reigned of the son of Ahaziah did Jehoshaphat," )
    , ( "ᛯ", "And it went our meat trees between an lover, and by the gates." )
    , ( "ᛯ", "Colai unto Saul, saying, Behold, I will evil daubs flame there in the orous." )
    , ( "ᛯ", "Now with her staff, which he ammy, that Gilead is neally of the spirit." )
    , ( "ᛯ", "And; in their fathers wait up for that it or truth was hasteth with her, saying," )
    , ( "ᛯ", "And I will pass them; for the perfign tribute, to lay their place." )
    , ( "ᛯ", "He hath said, Who was in chief famine of heavens, all his place." )
    , ( "ᛯ", "And the people that I son of Elubiah, and Ahbab, and one that toward the word." )
    , ( "ᛯ", "Wherefore heard as Samaria to the law and passegue of silence." )
    , ( "ᛯ", "They are in the congregation of the secumline more fear burnt and be consumed." )
    , ( "ᛯ", "Dothon went into his manner, they that woman and keep us to deliver they kizron." )
    , ( "ᛯ", "They may devour the place, that was called the foundation of the feet, my God." )
    , ( "ᛯ", "For I more thou hast husbadah gone until the land of the earth." )
    , ( "ᛯ", "And Jehoshaphat shall put them, and pass over addronds to high heart." )
    , ( "ᛯ", "Then they may go into buildres of the number of the house of the lips?" )
    , ( "ᛯ", "Now comfort me with him fell in, rebellior it: menth the garments, did blind?" )
    , ( "ᛯ", "And Samuel went in thy lion be given the slumbers by their honey." )
    , ( "ᛯ", "It is in the intears, there ready and found him: but he shall be at thy bed." )
    , ( "ᛯ", "And the king be sleep is plain that he comings into thee belary." )
    , ( "ᛯ", "But if it came to make one over full of the bread of their cornerp." )
    , ( "ᛯ", "And he took Pharaoh's fear, and what shall die? and fell this part of Bethlehe." )
    , ( "ᛯ", "The fourthertedst took him, seek by Payeshed, Evibea was ourishes of the city?" )
    , ( "ᛯ", "And it came to pass in the instliver, and the king served thee with an altar." )
    , ( "ᛯ", "For thine hundred living was thy servants: so that thou shut the thigh slaughter." )
    , ( "ᛯ", "Then Hanoursa the Horew had enquiry; The king is good trespire." )
    , ( "ᛯ", "Because the strange cubit with bars, after the king's neighbour's side answer." )
    , ( "ᛯ", "Hath his son, and a thing whereost shall be written unto the skin of Israel?" )
    , ( "ᛯ", "And they that forsaketh me, and he hath weptiless ye are under Eshua my goodness." )
    , ( "ᛯ", "Thou shalt not be judge for Babylon, and said unto the wavely." )
    , ( "ᛯ", "Hithour honour of evil left not, nor me in myself, which should I please Israel." )
    , ( "ᛯ", "SAcraies against Hana, and did endureth unto Joceph, and Zidnias." )
    , ( "ᛯ", "Yet the way upon the cuncir placians of the ten standing stranger." )
    , ( "ᛯ", "And the children of Israel said unto the LORD before him unto it:." )
    , ( "ᛯ", "Give also the lad over Israel; for there is no end out of the orgritaciseous." )
    , ( "ᛯ", "Thou wilt walking they shall be no herded, and sat there I maketh down arroce." )
    , ( "ᛯ", "All the strong and twenty years, neither will shew mess the moved." )
    , ( "ᛯ", "Their youngest is sick; and they had inheritants to be white and home round about." )
    , ( "ᛯ", "And the house sit out, and lie, one beloved art thy name's heart off." )
    , ( "ᛯ", "And when thou pledy than the bread of the evening pit of thy camb." )
    , ( "ᛯ", "Yea, lift to me it of the small men, and with us give down them." )
    , ( "ᛯ", "And Abihu didstal, and destroy them so, from the guald creepent." )
    , ( "ᛯ", "By the women were pestilence, I will not eateth joy upon thee unto the prument:" )
    , ( "ᛯ", "And after the inhils shall come to pass; art the cedgestation." )
    , ( "ᛯ", "Then we comfort our veasurest unto the sword shalt was wise mine house." )
    , ( "ᛯ", "And the Phultiter into the caves of the earth is early die, your kind." )
    , ( "ᛯ", "Thou shalt give them of the face; for they fall in the inheritance of Solomon." )
    , ( "ᛯ", "Behold, the words are all the voice: and if the LORD said, Verily Abner, saying," )
    , ( "ᛯ", "And thee hanged the king Danowibeh said, Gave him in the month:" )
    , ( "ᛯ", "And Moses had done thy face for it, seek unto the LORD their head, They live." )
    , ( "ᛯ", "And the LORD holieth beasts he was upon the sight of the sheep." )
    , ( "ᛯ", "The wickedness sparece my famils they are in the sin offering;" )
    , ( "ᛯ", "And Bethlehim, The LORD our God hath setwalvoweth the country." )
    , ( "ᛯ", "Fiercorined waxed way, and thou hast made many with all night." )
    , ( "ᛯ", "When he maketh the not saw that I shall die, and they turned Baals." )
    , ( "ᛯ", "If thou killed any border unto the halt, and knowledge with a sweet small thereon:" )
    , ( "ᛯ", "And I brought me forth, and wherein I beautione by thousaners." )
    , ( "ᛯ", "Take thou wisdom in pieces unto the altoner of his horn's burden:" )
    , ( "ᛯ", "He that dwell forth three upon the wickest, even all the poor is place." )
    , ( "ᛯ", "I am the heavens with pledge than they that corn to prove your unclean's high:" )
    , ( "ᛯ", "Then may keep a soul, and a band by Gibeemon, to devour I rested;" )
    , ( "ᛯ", "And it came to pass, within are not, and be called to Jabbaim before." )
    , ( "ᛯ", "Nevertheleth broken me, I beside herthoved, and son unto Jacob." )
    , ( "ᛯ", "When the own trees of the sons of Ram, and unto Moses have peace." )
    , ( "ᛯ", "Let me the priests Abner of Sashite, the Hittite instead of Beershelech;" )
    , ( "ᛯ", "Elijah was song Undezers, and kings are filled meat number thereon." )
    , ( "ᛯ", "Thou shalt not eat the good thing is none; and for me in the battle of the tribe." )
    , ( "ᛯ", "Then shall they do: for therefore, shalt thou make any strange rose," )
    , ( "ᛯ", "Then reigned beaten shout to shame, for his priest, it of iniquity." )
    , ( "ᛯ", "And they will not able to be given to the king's house and honey." )
    , ( "ᛯ", "They bring it unto thee, and the high place and scarb is thy name." )
    , ( "ᛯ", "And it came to pass, Aaron's coast, a thousand been I know it;" )
    , ( "ᛯ", "Out imagine seasons of fambucls, and dwellest kindets, fifty and hivers." )
    , ( "ᛯ", "And Aaron brakingly upon me? whether for a lothing fair from find?" )
    , ( "ᛯ", "The sons of Jehoash answered, let them go ye, Thus so shall I did say unto Jacob." )
    , ( "ᛯ", "And such among the singers of the LORD because that the LORD is his holined." )
    , ( "ᛯ", "Of the sons of Judah, and gold, and all, and they geter to rest." )
    , ( "ᛯ", "Fear of my servant; and a thousture, that these were city there be for them:" )
    , ( "ᛯ", "And they shall come to Jerusamin, of the kings of Israel: yet be giveth it." )
    , ( "ᛯ", "Even the night all evil for this used led after the mighty men of Israel." )
    , ( "ᛯ", "And he spake unto the LORD, who then thy eaven their corrists with stones?" )
    , ( "ᛯ", "Is the people thing put forward, and his inheritance of the river ye desire." )
    , ( "ᛯ", "Shall the LORD amencheth me unto the leaven and two morrow, and hast thou make us." )
    , ( "ᛯ", "And thou said, Thou art righteousness, they are with the days, saith the LORD." )
    , ( "ᛯ", "And there be well like me, and the prophets, and the one thing was old:" )
    , ( "ᛯ", "I will be afraid at the bary against the Anothon, and without greatness." )
    , ( "ᛯ", "Son of man, make thee unto the LORD had brought from the half trouble." )
    , ( "ᛯ", "Wherefore have I judge for a neverbanit is the people of Lebenah, of a work?" )
    , ( "ᛯ", "The LORD departed, and came uptains, the river of Abijah's openy." )
    , ( "ᛯ", "It is the kingdom, and they turneth befallester: they flay the way of heavens." )
    , ( "ᛯ", "And Naphtike generath sown yet in Gilmam the young lamb, Jeremiah was not mourn." )
    , ( "ᛯ", "And it called the earth shall come up from the river for heart." )
    , ( "ᛯ", "And Benaim made Sarah with her, and they set it unto Dan out of the bread." )
    , ( "ᛯ", "And on the children of the other syich thou were against his firstborn for her." )
    , ( "ᛯ", "Who tepthier he that sacrifice there a pather, for ever thereof.)" )
    , ( "ᛯ", "Yet no destroyer after all her your ears, which was not for thy kundoes." )
    , ( "ᛯ", "But if the people shall go out to he be, until he hath prepand straightne." )
    , ( "ᛯ", "He shall not hear any for you, and she shall weary been there." )
    , ( "ᛯ", "Their man king Amnon sent of silver and terrible another, shall all word." )
    , ( "ᛯ", "And the LORD commanded the priests im. And he said, Remon Jeromon's mother." )
    , ( "ᛯ", "All ow with all that they may beaten by the city before: and the with me." )
    , ( "ᛯ", "And when he shall give up in Chaldee and fields, for heaven shall be in thee." )
    , ( "ᛯ", "Peaded the wings of the children of Cheshbom, he shall perish it." )
    , ( "ᛯ", "Thus saith the LORD of hosts; heareth none of brisons for nothing." )
    , ( "ᛯ", "He poured alate, said him, The prey, neither was deceit, the host casted and said." )
    , ( "ᛯ", "And I beast Syria, saying risen other money against Moses unto them." )
    , ( "ᛯ", "Then I have given me by an abrimsed: for when Haraah is a meat." )
    , ( "ᛯ", "And if the steps was of thy servants, and thus Arishal the singer that arosting?" )
    , ( "ᛯ", "And thou shalt not sinned, then they have for full thereof of many:" )
    , ( "ᛯ", "He hath devoured him the world and a man that bring them carry us." )
    , ( "ᛯ", "I will small direce to the inhabitle an Airchmosh, Jain, and Jeshai turneth." )
    , ( "ᛯ", "And Abraham and thy faces were and all those things of every hand?" )
    , ( "ᛯ", "And they perform lift king Migroshest, the house, O LORD, surely shewed Moses." )
    , ( "ᛯ", "And there shall be the top of your enemies was and poured shall be opened." )
    , ( "ᛯ", "And if there believe him that they answered and wet iniquity for the ass," )
    , ( "ᛯ", "The way of the gates sinnet that is twenty out of the name? or in his sons." )
    , ( "ᛯ", "And passed upon the stead of Aaron, and the earth, to turn above any girdle." )
    , ( "ᛯ", "Now God do the gods of the vineyards for this day of fire astonied." )
    , ( "ᛯ", "And when I shall search a return upon the countriast of the LORD's God." )
    , ( "ᛯ", "Camuch smoke away, surely buildeth they in the land, or by the LORD." )
    , ( "ᛯ", "When Sodom searcify yecations hath taken out of them to blow God;" )
    , ( "ᛯ", "When the hallow war together unto him: that that the LORD thy youth." )
    , ( "ᛯ", "And the dust more have I giveth up up the see that are righteous." )
    , ( "ᛯ", "And that the talents which fell down for uncle from the cattle." )
    , ( "ᛯ", "And Zedekiah him petylon in all upon that of long both to meek with him." )
    , ( "ᛯ", "But he died, I smotion in the light of them that were asmon before your fathers." )
    , ( "ᛯ", "And these are made in all thy most, that forget not their sign in his master." )
    , ( "ᛯ", "And after the tables therefore there is a compared from thy sign in the house." )
    , ( "ᛯ", "Thou shalt not deal grasshon, while I will could not offer not confurion." )
    , ( "ᛯ", "That it with the prouds of thy statutes, and thou knowest man." )
    , ( "ᛯ", "Then said Gillah, and multiply he served: therefore departeth evil in furion." )
    , ( "ᛯ", "Their master's priest stars' cannot slew me? Shall ye shall be given rendest good." )
    , ( "ᛯ", "My bownies shall be thy flour for the will of thy light and thy feat." )
    , ( "ᛯ", "Also Jehu went once down, and to meet me, neither these open and horses." )
    , ( "ᛯ", "God amend wives and fat thy horn: but he thundered a day of his tooth." )
    , ( "ᛯ", "And thy time was no glory by the blood, and thou says and said, Call." )
    , ( "ᛯ", "When the LORD commit allaged the blind, and Halmanah where thou camest utter thee?" )
    , ( "ᛯ", "For there was not the sight deliverance: the fire end from the words." )
    , ( "ᛯ", "Firress shall I, then ye before thy LORD, joy they be graft round about." )
    , ( "ᛯ", "Then were able thine own land; and what they coming against you desolate." )
    , ( "ᛯ", "He run after it, neither did from off, or strong wheat on the given out." )
    , ( "ᛯ", "If it was dried by a ways, or in Tay, and the dead was peace offering a eyes." )
    , ( "ᛯ", "And the king thy yoke unto thee speaketh, Is Hazor shall not there." )
    , ( "ᛯ", "And halfflumuty and Judah, and said unto his sinnels over the moins." )
    , ( "ᛯ", "And it shall come into their great blood of men; as sixty afraid of Jericht;" )
    , ( "ᛯ", "And therefore the wicked and no later; and I will not received David." )
    , ( "ᛯ", "The second beside the rest of the righteous, and will she wives to prepared." )
    , ( "ᛯ", "It shall be festlish, his son crieth: I am he delivered the home ungodly, saying," )
    , ( "ᛯ", "The family of the Egyptians shall be dust as in the pledge of the LORD." )
    , ( "ᛯ", "The LORD thy God came no lawful; and I will digged with children." )
    , ( "ᛯ", "And the sons of the Jebusites, which are looking before Israel." )
    , ( "ᛯ", "And Nonah oppressed all them when ye have mattered out at Mageed." )
    , ( "ᛯ", "For there is far ye more fall, and shall did I wrath from the battle." )
    , ( "ᛯ", "The sons of Jesus have gathered the norty life, and take a lamed of Jacioan?" )
    , ( "ᛯ", "And said unto her, I shame twentieth day of Zobah, and Saul, one." )
    , ( "ᛯ", "But the God of Sodom and Zabot, and hear thou hids an where of the LORD to do." )
    , ( "ᛯ", "But I life make a disciples and in many people after thy soul." )
    , ( "ᛯ", "And it cast thou destruction filled: he came to the host of the amproach," )
    , ( "ᛯ", "So Jehoahaz his sinst he upon the land which thou shalt read themselves." )
    , ( "ᛯ", "And he take not the word of Oben, and to David better king go up?" )
    , ( "ᛯ", "And Jonathaphan king of the breast liest thine iniquity for ever." )
    , ( "ᛯ", "And the word flee in mine hand, and be, ye shall take his daughters for a gatrees." )
    , ( "ᛯ", "He mine eye sons in, accold the heads of the children of Nebah:" )
    , ( "ᛯ", "Then he was driven shalt thou not do according to the kids of the LORD undelare?" )
    ]


divineTextsGerman : List ( String, String )
divineTextsGerman =
    [ ( "Num 32:40", "Da gab Mose dem Machir, dem Sohn Manasses, Gilead; und er wohnte darin." )
    , ( "Psa 119:125", "Ich bin dein Knecht; unterweise mich, dass ich erkenne deine Zeugnisse." )
    , ( "1Co 10:31", "Ihr esset nun oder trinket oder was ihr tut, so tut es alles zu Gottes Ehre." )
    , ( "Psa 106:35", "sondern sie mengten sich unter die Heiden und lernten derselben Werke" )
    , ( "Psa 84:5", "Wohl denen, die in deinem Hause wohnen; die loben dich immerdar. (Sela.)" )
    , ( "Heb 10:14", "Denn mit einem Opfer hat er in Ewigkeit vollendet, die geheiligt werden." )
    , ( "Joh 19:22", "Pilatus antwortete: Was ich geschrieben habe, das habe ich geschrieben." )
    , ( "Psa 112:6", "Denn er wird ewiglich bleiben; des Gerechten wird nimmermehr vergessen." )
    , ( "Sol 1:14", "Mein Freund ist mir eine Traube von Zyperblumen in den Weinbergen zu Engedi." )
    , ( "Isa 8:13", "sondern heiliget den HERRn Zebaoth. Den lasset eure Furcht und Schrecken sein," )
    , ( "Amo 7:3", "Da reute es den HERRn und er sprach: Wohlan, es soll nicht geschehen." )
    , ( "Rev 2:6", "Aber das hast du, dass du die Werke der Nikolaiten hassest, welche ich auch hasse." )
    , ( "Rom 11:34", "Denn wer hat des Herrn Sinn erkannt, oder wer ist sein Ratgeber gewesen?" )
    , ( "Psa 119:93", "Ich will deine Befehle nimmermehr vergessen; denn du erqickest mich damit." )
    , ( "Psa 118:22", "Der Stein, den die Bauleute verworfen haben, ist zum Eckstein geworden." )
    , ( "Gen 43:13", "Dazu nehmt euren Bruder, macht euch auf und kommt wieder zu dem Manne." )
    , ( "Gen 21:5", "Hundert Jahre war Abraham alt, da ihm sein Sohn Isaak geboren ward." )
    , ( "2Ti 4:4", "und werden die Ohren von der Wahrheit wenden und sich zu Fabeln kehren." )
    , ( "1Sa 25:43", "Auch hatte David Ahinoam von Jesreel genommen; und waren beide seine Weiber." )
    , ( "Exo 19:14", "Mose stieg vom Berge zum Volk und heiligte sie, und sie wuschen ihre Kleider." )
    , ( "Psa 94:3", "HERR, wie lange sollen die Gottlosen, wie lange sollen die Gottlosen prahlen" )
    , ( "Luk 16:12", "Und so ihr in dem Fremden nicht treu seid, wer wird euch geben, was euer ist?" )
    , ( "1Ch 5:19", "Und sie stritten mit den Hagaritern und mit Jetur, Naphis und Nodab;" )
    , ( "Pro 29:13", "Arme und Reiche begegnen einander: beider Augen erleuchtet der HERR." )
    , ( "Exo 12:50", "Und alle Kinder Israel taten, wie der HERR Mose und Aaron hatte geboten." )
    , ( "Lev 7:1", "Und dies ist das Gesetz des Schuldopfers. Ein Hochheiliges ist es." )
    , ( "1Th 2:6", "haben auch nicht Ehre gesucht von den Leuten, weder von euch noch von andern;" )
    , ( "Tit 3:10", "Einen ketzerischen Menschen meide, wenn er einmal und abermals ermahnt ist," )
    , ( "Gen 13:15", "Denn alles Land, das du siehst, will ich dir geben und deinem Samen ewiglich;" )
    , ( "Job 39:17", "Denn Gott hat ihm die Weisheit genommen und hat ihm keinen Verstand zugeteilt." )
    , ( "Mar 3:3", "Und er sprach zu dem Menschen mit der verdorrten Hand: Tritt hervor!" )
    , ( "Mat 26:27", "Und er nahm den Kelch und dankte, gab ihnen den und sprach: Trinket alle daraus;" )
    , ( "Jdg 20:29", "Und die Kinder Israel stellten einen Hinterhalt auf Gibea umher." )
    , ( "1Ch 11:34", "die Kinder Hasems, des Gisoniters; Jonathan, der Sohn Sages, der Harariter;" )
    , ( "Jos 15:20", "Dies ist das Erbteil des Stammes der Kinder Juda nach ihren Geschlechtern." )
    , ( "Luk 1:73", "und an den Eid, den er geschworen hat unsrem Vater Abraham, uns zu geben," )
    , ( "2Th 3:18", "Die Gnade unsres Herrn Jesu Christi sei mit euch allen! Amen." )
    , ( "1Sa 13:23", "Und eine Wache der Philister zog heraus an den engen Weg von Michmas." )
    , ( "1Ch 23:20", "Die Kinder Usiels waren, Micha, der erste, und Jissia, der andere." )
    , ( "Psa 83:9", "Assur hat sich auch zu ihnen geschlagen; sie helfen den Kindern Lot. (Sela.)" )
    , ( "1Ch 26:27", "(Von Krieg und Raub hatten sie es geheiligt, zu bessern das Haus des HERRn.)" )
    , ( "Rom 9:18", "So erbarmt er sich nun, welches er will, und verstockt, welchen er will." )
    , ( "Psa 36:10", "Denn bei dir ist die Quelle des Lebens, und in deinem Licht sehen wir das Licht." )
    , ( "Pro 23:1", "Wenn du sitzest und issest mit einem Herrn, so merke, wen du vor dir hast," )
    , ( "Pro 12:16", "Ein Narr zeigt seinen Zorn alsbald; aber wer die Schmach birgt, ist klug." )
    , ( "1Co 11:8", "Denn der Mann ist nicht vom Weibe, sondern das Weib vom Manne." )
    , ( "Psa 50:20", "Du sitzest und redest wider deinen Bruder; deiner Mutter Sohn verleumdest du." )
    , ( "Psa 38:18", "Denn ich bin zu Leiden gemacht, und mein Schmerz ist immer vor mir." )
    , ( "Ezr 10:31", "unter den Kindern Harim: Elieser, Jissia, Malchia, Semaja Simeon," )
    , ( "Abd 1:2", "Siehe, ich habe dich gering gemacht unter den Heiden und sehr verachtet." )
    , ( "Eze 48:3", "Neben Asser soll Naphthali seinen Teil haben, von Morgen bis gen Abend." )
    , ( "1Jo 5:7", "Denn drei sind, die da zeugen: der Geist und das Wasser und das Blut;" )
    , ( "Isa 22:20", "Und zu der Zeit will ich rufen meinen Knecht Eljakim, den Sohn Hilkias," )
    , ( "Pro 3:30", "Hadere nicht mit jemand ohne Ursache, so er dir kein Leid getan hat." )
    , ( "Eze 3:16", "Und da die sieben Tage um waren, geschah des HERRn Wort zu mir und sprach:" )
    , ( "Pro 11:16", "Ein holdselig Weib erlangt Ehre; aber die Tyrannen erlangen Reichtum." )
    , ( "Exo 18:15", "Mose antwortete ihm: Das Volk kommt zu mir, Gott um Rat zu fragen." )
    , ( "Psa 119:141", "Ich bin gering und verachtet; ich vergesse aber nicht deiner Befehle." )
    , ( "Psa 113:1", "Halleluja! Lobet, ihr Knechte des HERRn, lobet den Namen des HERRn!" )
    , ( "Luk 7:5", "denn er hat unser Volk lieb, und die Schule hat er uns erbaut." )
    , ( "Psa 119:150", "Meine boshaften Verfolger nahen herzu und sind ferne von deinem Gesetz." )
    , ( "1Sa 15:31", "Also kehrte Samuel um und folgte Saul nach, dass Saul den HERRn anbetete." )
    , ( "2Sa 22:22", "Denn ich halte die Wege des HERRn und bin nicht gottlos wider meinen Gott." )
    , ( "Psa 135:19", "Das Haus Israel lobe den HERRn! Lobet den HERRn, ihr vom Hause Aaron!" )
    , ( "Pro 23:30", "Wo man beim Wein liegt und kommt, auszusaufen, was eingeschenkt ist." )
    , ( "Exo 36:20", "Und machte Bretter zur Wohnung von Akazienholz, die stehen sollten," )
    , ( "Jer 5:18", "Doch will ich's, spricht der HERR, zur selben Zeit mit euch nicht gar aus machen." )
    , ( "Mat 27:49", "Die andern aber sprachen: Halt, lass sehen, ob Elia komme und ihm helfe." )
    , ( "Phi 4:20", "Gott aber, unsrem Vater, sei Ehre von Ewigkeit zu Ewigkeit! Amen." )
    , ( "Psa 44:8", "sondern du hilfst uns von unsren Feinden und machst zu Schanden, die uns hassen." )
    , ( "Eze 7:23", "Mache Ketten; denn das Land ist voll Blutschulden und die Stadt voll Frevels." )
    , ( "Pro 13:23", "Es ist viel Speise in den Furchen der Armen; aber die Unrecht tun, verderben." )
    , ( "Joh 5:17", "Jesus aber antwortete Ihnen: Mein Vater wirkt bisher, und ich wirke auch." )
    , ( "Psa 106:8", "Er half ihnen aber um seines Namens willen, dass er seine Macht bewiese." )
    , ( "Psa 15:2", "Wer ohne Tadel einhergeht und recht tut und redet die Wahrheit von Herzen;" )
    , ( "Isa 9:7", "Der HERR hat sein Wort gesandt in Jakob, und es ist in Israel gefallen," )
    , ( "Act 15:15", "Und damit stimmen der Propheten Reden, wie geschrieben steht:" )
    , ( "Lam 5:15", "Unsres Herzens Freude hat ein Ende; unser Reigen ist in Wehklagen verkehrt." )
    , ( "Psa 108:2", "Gott, es ist mein rechter Ernst; ich will singen und dichten, meine Ehre auch." )
    , ( "Gen 46:16", "Die Kinder Gads: Ziphjon, Haggi, Suni, Ezbon, Eri, Arodi und Areli." )
    , ( "Neh 11:36", "Und etliche Leviten, die Teile in Juda hatten, wohnten unter Benjamin." )
    , ( "Gen 7:22", "Alles, was einen lebendigen Odem hatte auf dem Trockenen, das starb." )
    , ( "Psa 104:20", "Du machst Finsternis, dass es Nacht wird; da regen sich alle wilden Tiere," )
    , ( "Gen 11:26", "Tharah war siebzig Jahre alt und zeugte Abram, Nahor und Haran." )
    , ( "Exo 26:20", "Also auf der andern Seite gegen Mitternacht sollen auch zwanzig Bretter stehen" )
    , ( "1Ki 20:18", "Er sprach: Greift sie lebendig, sie seien um Friedens oder um Streit ausgezogen!" )
    , ( "Joh 18:24", "Und Hannas sandte ihn gebunden zu dem Hohenpriester Kaiphas." )
    , ( "1Ch 1:29", "Dies ist ihr Geschlecht: der erste Sohn Ismaels, Nebajoth, Kedar, Adbeel, Mibsam," )
    , ( "Deu 25:12", "so sollst du ihr die Hand abhauen, und dein Auge soll sie nicht verschonen." )
    , ( "Joh 8:17", "Auch steht in eurem Gesetz geschrieben, dass zweier Menschen Zeugnis wahr sei." )
    , ( "Luk 23:13", "Pilatus aber rief die Hohenpriester und die Obersten und das Volk zusammen" )
    , ( "Joh 4:16", "Jesus spricht zu ihr: Gehe hin, rufe deinen Mann und komm her!" )
    , ( "Pro 28:23", "Wer einen Menschen straft, wird hernach Gunst finden, mehr denn der da heuchelt." )
    , ( "Psa 81:5", "Denn solches ist die Weise in Israel und ein Recht des Gottes Jakobs." )
    , ( "1Sa 19:14", "Da sandte Saul Boten, dass sie David holten. Sie aber sprach: Er ist krank." )
    , ( "Joh 6:33", "Denn dies ist das Brot Gottes, das vom Himmel kommt und gibt der Welt das Leben." )
    , ( "2Ch 31:9", "Und Hiskia fragte die Priester und die Leviten um die Haufen." )
    , ( "Psa 104:27", "Es wartet alles auf dich, dass du ihnen Speise gebest zu seiner Zeit." )
    , ( "Psa 39:10", "Ich will schweigen und meinen Mund nicht auftun; denn du hast's getan." )
    , ( "Lev 20:7", "Darum heiligt euch und seid heilig; denn ich bin der HERR, euer Gott." )
    , ( "2Ch 14:1", "Und Asa tat, was recht war und dem HERRn, seinem Gott, wohl gefiel," )
    , ( "Pro 4:22", "Denn sie sind das Leben denen, die sie finden, und gesund ihrem ganzen Leibe." )
    , ( "Psa 71:1", "HERR, ich traue auf dich; lass mich nimmermehr zu Schanden werden." )
    , ( "Num 26:61", "Nadab aber und Abihu starben, da sie fremdes Feuer opferten vor dem HERRn." )
    , ( "Exo 4:13", "Mose sprach aber: Mein Herr, sende, welchen du senden willst." )
    , ( "Exo 20:9", "Sechs Tage sollst du arbeiten und alle dein Dinge beschicken;" )
    , ( "1Ki 14:30", "Es war aber Krieg zwischen Rehabeam und Jerobeam ihr Leben lang." )
    , ( "Heb 11:14", "Denn die solches sagen, die geben zu verstehen, dass sie ein Vaterland suchen." )
    , ( "Psa 73:21", "Da es mir wehe tat im Herzen und mich stach in meinen Nieren," )
    , ( "Mic 6:11", "Oder sollte ich die unrechte Waage und falsche Gewichte im Beutel billigen," )
    , ( "Joh 2:3", "Und da es an Wein gebrach, spricht die Mutter Jesu zu ihm: Sie haben nicht Wein." )
    , ( "Psa 52:6", "Du redest gerne alles, was zu verderben dient, mit falscher Zunge." )
    , ( "1Ch 2:33", "Die Kinder aber Jonathans sind: Peleth und Sasa. Das sind die Kinder Jerahmeels." )
    , ( "Ecc 2:2", "Ich sprach zum Lachen: Du bist toll! und zur Freude: Was machst du?" )
    , ( "Psa 51:20", "Tue wohl an Zion nach deiner Gnade; baue die Mauern zu Jerusalem." )
    , ( "Deu 31:25", "gebot er den Leviten, die die Lade des Zeugnisses des HERRn trugen, und sprach:" )
    , ( "Psa 118:28", "Du bist mein Gott, und ich danke dir; mein Gott, ich will dich preisen." )
    , ( "Ezr 8:7", "von den Kindern Elam: Jesaja, der Sohn Athaljas, und mit ihm siebzig Mannsbilder;" )
    , ( "Jer 13:5", "Ich ging hin und versteckte ihn am Euphrat, wie mir der HERR geboten hatte." )
    , ( "1Ch 4:11", "Kalub aber, der Bruder Suhas, zeugte Mehir; der ist der Vater Esthons." )
    , ( "1Co 14:13", "Darum, welcher mit Zungen redet, der bete also, dass er's auch auslege." )
    , ( "Gen 36:25", "Die Kinder aber Anas waren: Dison und Oholibama, das ist die Tochter Anas." )
    , ( "Lev 25:13", "Das ist das Halljahr, da jedermann wieder zu dem Seinen kommen soll." )
    , ( "Psa 116:2", "Denn er neigte sein Ohr zu mir; darum will ich mein Leben lang ihn anrufen." )
    , ( "1Ch 7:25", "Des Sohn war Repha und Reseph; des Sohn war Thelah; des Sohn war Thahan;" )
    , ( "Act 10:40", "Den hat Gott auferweckt am dritten Tage und ihn lassen offenbar werden," )
    , ( "Psa 119:15", "Ich rede von dem, was du befohlen hast, und schaue auf deine Wege." )
    , ( "Psa 73:17", "bis dass ich ging in das Heiligtum Gottes und merkte auf ihr Ende." )
    , ( "2Sa 1:7", "Und er wandte sich um und sah mich und rief mich. Und ich sprach: Hier bin ich." )
    , ( "Ecc 7:16", "Sei nicht allzu gerecht und nicht allzu weise, dass du dich nicht verderbest." )
    , ( "Joh 8:32", "und werdet die Wahrheit erkennen, und die Wahrheit wird euch frei machen." )
    , ( "Mat 25:46", "Und sie werden in die ewige Pein gehen, aber die Gerechten in das ewige Leben." )
    , ( "Psa 18:22", "Denn ich halte die Wege des HERRn und bin nicht gottlos wider meinen Gott." )
    , ( "Jdg 12:11", "Nach diesem richtete Israel Elon, ein Sebuloniter; er richtete Israel zehn Jahre" )
    , ( "Num 32:10", "Und des HERRn Zorn ergrimmte zur selben Zeit, und er schwur und sprach:" )
    , ( "Mat 24:20", "Bittet aber, dass eure Flucht nicht geschehe im Winter oder am Sabbat." )
    , ( "Joh 15:3", "Ihr seid schon rein um des Wortes willen, das ich zu euch geredet habe." )
    , ( "Est 4:17", "Mardochai ging hin und tat alles, was ihm Esther geboten hatte." )
    , ( "Num 2:4", "und sein Heer, zusammen vierundsiebzigtausend und sechshundert." )
    , ( "Joh 6:56", "Wer mein Fleisch isset und trinket mein Blut, der bleibt in mir und ich in ihm." )
    , ( "Gen 10:13", "Mizraim zeugte die Luditer, die Anamiter, die Lehabiter, die Naphthuhiter," )
    , ( "Psa 9:8", "Der HERR aber bleibt ewiglich; er hat seinen Stuhl bereitet zum Gericht," )
    , ( "Psa 119:112", "Ich neige mein Herz, zu tun nach deinen Rechten immer und ewiglich." )
    , ( "Mat 14:25", "Aber in der vierten Nachtwache kam Jesus zu ihnen und ging auf dem Meer." )
    , ( "Phm 1:25", "Die Gnade unsres Herrn Jesu Christi sei mit eurem Geist! Amen." )
    , ( "Mar 10:44", "und welcher unter euch will der Vornehmste werden, der soll aller Knecht sein." )
    , ( "Num 5:29", "Dies ist das Eifergesetz, wenn ein Weib ihrem Mann untreu ist und unrein wird," )
    , ( "Job 9:22", "Es ist eins, darum sage ich: Er bringt um beide, den Frommen und den Gottlosen." )
    , ( "Luk 21:33", "Himmel und Erde werden vergehen; aber meine Worte vergehen nicht." )
    , ( "Psa 97:4", "Seine Blitze leuchten auf den Erdboden; das Erdreich siehet's und erschrickt." )
    , ( "Exo 35:9", "Onyxsteine und eingefasste Steine zum Leibrock und zum Amtschild." )
    , ( "1Ch 18:12", "Und Abisai, der Zeruja Sohn, schlug der Edomiter im Salztal achtzehntausend" )
    , ( "2Co 6:12", "Ihr habt nicht engen Raum in uns; aber eng ist's in euren Herzen." )
    , ( "Job 41:13", "Sein Odem ist wie eine lichte Lohe, und aus seinem Munde gehen Flammen." )
    , ( "Psa 103:7", "Er hat seine Wege Mose wissen lassen, die Kinder Israel sein Tun." )
    , ( "Pro 30:29", "Dreierlei haben einen feinen Gang, und das vierte geht wohl:" )
    , ( "Num 22:2", "Und Balak, der Sohn Zippors, sah alles, was Israel getan hatte den Amoritern;" )
    , ( "Gen 3:4", "Da sprach die Schlange zum Weibe: Ihr werdet mitnichten des Todes sterben;" )
    , ( "Job 7:12", "Bin ich denn ein Meer oder ein Meerungeheuer, dass du mich so verwahrst?" )
    , ( "Eze 16:2", "Du Menschenkind offenbare der Stadt Jerusalem ihre Greuel und sprich:" )
    , ( "Jos 16:4", "Das haben zum Erbteil genommen die Kinder Josephs, Manasse und Ephraim." )
    , ( "Num 9:4", "Und Mose redete mit den Kindern Israel, dass sie das Passah hielten." )
    , ( "Deu 6:19", "dass er verjage alle deine Feinde vor dir, wie der HERR geredet hat." )
    , ( "Pro 1:25", "und lasst fahren allen meinen Rat und wollt meine Strafe nicht:" )
    , ( "Job 38:7", "da mich die Morgensterne miteinander lobten und jauchzten alle Kinder Gottes?" )
    , ( "Hos 5:12", "Ich bin dem Ephraim wie eine Motte und dem Hause Juda wie eine Made." )
    , ( "Joh 11:43", "Da er das gesagt hatte, rief er mit lauter Stimme: Lazarus, komm heraus!" )
    , ( "Jos 13:29", "Dem halben Stamm der Kinder Manasse nach ihren Geschlechtern gab Mose," )
    , ( "Mat 24:18", "und wer auf dem Felde ist, der kehre nicht um, seine Kleider zu holen." )
    , ( "Job 23:4", "und das Recht vor ihm sollte vorlegen und den Mund voll Verantwortung fassen" )
    , ( "Psa 67:3", "dass man auf Erden erkenne seinen Weg, unter allen Heiden sein Heil." )
    , ( "Joh 6:50", "Dies ist das Brot, das vom Himmel kommt, auf dass, wer davon isset, nicht sterbe." )
    , ( "Lev 23:25", "da sollt ihr keine Dienstarbeit tun und sollt dem HERRn opfern." )
    , ( "Rom 15:25", "Nun aber fahre ich hin gen Jerusalem den Heiligen zu Dienst." )
    , ( "Psa 107:27", "dass sie taumelten und wankten wie ein Trunkener und wussten keinen Rat mehr;" )
    , ( "Job 6:3", "Denn nun ist es schwerer als Sand am Meer; darum gehen meine Worte irre." )
    , ( "Dan 2:19", "Da ward Daniel solch verborgenes Ding durch ein Gesicht des Nachts offenbart." )
    , ( "Luk 17:13", "und erhoben ihre Stimme und sprachen: Jesu, lieber Meister, erbarme dich unser!" )
    , ( "Psa 33:21", "Denn unser Herz freut sich sein, und wir trauen auf seinen heiligen Namen." )
    , ( "Job 27:16", "Wenn er Geld zusammenbringt wie Staub und sammelt Kleider wie Lehm," )
    , ( "Deu 5:4", "Er hat von Angesicht zu Angesicht mit euch aus dem Feuer auf dem Berge geredet." )
    , ( "Luk 4:32", "Und sie verwunderten sich seiner Lehre; denn seine Rede war gewaltig." )
    , ( "Luk 7:35", "Und die Weisheit muss sich rechtfertigen lassen von allen ihren Kindern." )
    , ( "1Ch 6:8", "des Sohn war Elkana; des Sohn war Abiasaph; des Sohn war Assir;" )
    , ( "Psa 148:8", "Feuer, Hagel, Schnee und Dampf, Sturmwinde, die sein Wort ausrichten;" )
    , ( "Luk 10:33", "Ein Samariter aber reiste und kam dahin; und da er ihn sah, jammerte ihn sein," )
    , ( "Pro 25:25", "Eine gute Botschaft aus fernen Landen ist wie kalt Wasser einer durstigen Seele." )
    , ( "Mat 28:17", "Und da sie ihn sahen, fielen sie vor ihm nieder; etliche aber zweifelten." )
    , ( "2Ki 6:7", "Und er sprach: Heb's auf! da reckte er seine Hand aus und nahm's." )
    , ( "Joh 3:35", "Der Vater hat den Sohn lieb und hat ihm alles in seine Hand gegeben." )
    , ( "2Ch 2:12", "So sende ich nun einen weisen Mann, der Verstand hat, Huram, meinen Meister" )
    , ( "Psa 41:14", "Gelobet sei der HERR, der Gott Israels, von nun an bis in Ewigkeit! Amen, amen." )
    , ( "Lam 3:59", "Du siehest, HERR, wie mir so Unrecht geschieht; hilf mir zu meinem Recht!" )
    , ( "Psa 72:2", "dass er dein Volk richte mit Gerechtigkeit und deine Elenden rette." )
    , ( "1Ch 1:11", "Mizraim zeugte die Luditer, die Anamiter, die Lehabiter, die Naphthuhiter," )
    , ( "2Ki 7:20", "Und es ging ihm eben also; denn das Volk zertrat ihn im Tor, dass er starb." )
    , ( "Exo 33:14", "Er sprach: Mein Angesicht soll vorangehen; damit will ich dich leiten." )
    , ( "Deu 32:40", "Denn ich will meine Hand in den Himmel heben und will sagen: Ich lebe ewiglich." )
    , ( "2Sa 16:20", "Und Absalom sprach zu Ahithophel: Ratet zu, was sollen wir tun?" )
    , ( "3Jo 1:8", "So sollen wir nun solche aufnehmen, auf dass wir der Wahrheit Gehilfen werden." )
    , ( "Joh 8:50", "Ich suche nicht meine Ehre; es ist aber einer, der sie sucht, und richtet." )
    , ( "Mat 26:68", "und sprachen: Weissage uns, Christe, wer ist's, der dich schlug?" )
    , ( "Job 31:38", "Wird mein Land gegen mich schreien und werden miteinander seine Furchen weinen;" )
    , ( "Mar 7:20", "Und er sprach: Was aus dem Menschen geht, das macht den Menschen gemein;" )
    , ( "Act 20:36", "Und als er solches gesagt, kniete er nieder und betete mit ihnen allen." )
    , ( "Psa 34:16", "Die Augen des HERRn merken auf die Gerechten und seine Ohren auf ihr Schreien;" )
    , ( "Act 4:11", "Das ist der Stein, von euch Bauleuten verworfen, der zum Eckstein geworden ist." )
    , ( "Pro 7:19", "Denn der Mann ist nicht daheim; er ist einen fernen Weg gezogen." )
    , ( "Psa 148:5", "Die sollen loben den Namen des HERRn; denn er gebot, da wurden sie geschaffen." )
    , ( "Mat 6:12", "Und vergib uns unsre Schuld, wie wir unsren Schuldigern vergeben." )
    , ( "Pro 31:14", "Sie ist wie ein Kaufmannsschiff, das seine Nahrung von ferne bringt." )
    , ( "Gen 21:34", "Und er war ein Fremdling in der Philister Lande eine lange Zeit." )
    , ( "Ecc 7:3", "Es ist Trauern besser als Lachen; denn durch Trauern wird das Herz gebessert." )
    , ( "Psa 50:17", "so du doch Zucht hassest und wirfst meine Worte hinter dich?" )
    , ( "Gen 44:25", "Da sprach unser Vater: Ziehet wieder hin und kauft uns ein wenig Speise." )
    , ( "Joh 1:28", "Dies geschah zu Bethabara jenseit des Jordans, wo Johannes taufte." )
    , ( "1Co 15:7", "Darnach ist er gesehen worden von Jakobus, darnach von allen Aposteln." )
    , ( "Isa 6:12", "Denn der HERR wird die Leute fern wegtun, dass das Land sehr verlassen wird." )
    , ( "Mar 3:24", "Wenn ein Reich mit sich selbst uneins wird, kann es nicht bestehen." )
    , ( "Jos 4:22", "So sollt ihr's ihnen kundtun und sagen: Israel ging trocken durch den Jordan," )
    , ( "Num 31:11", "Und nahmen allen Raub und alles, was zu nehmen war, Menschen und Vieh," )
    , ( "Pro 19:24", "Der Faule verbirgt seine Hand im Topf und bringt sie nicht wieder zum Munde." )
    , ( "Luk 22:28", "Ihr aber seid's, die ihr beharrt habt bei mir in meinen Anfechtungen." )
    , ( "Rev 21:26", "Und man wird die Herrlichkeit und die Ehre der Heiden in sie bringen." )
    , ( "Num 13:25", "Und sie kehrten um, als sie das Land erkundet hatten, nach vierzig Tagen," )
    , ( "Psa 142:2", "Ich schreie zum HERRn mit meiner Stimme; ich flehe zum HERRn mit meiner Stimme;" )
    , ( "Job 33:2", "Siehe, ich tue meinen Mund auf, und meine Zunge redet in meinem Munde." )
    , ( "Pro 1:29", "Darum, dass sie hassten die Lehre und wollten des HERRn Furcht nicht haben," )
    , ( "Psa 130:6", "Meine Seele wartet auf den HERRn von einer Morgenwache bis zur andern." )
    , ( "2Ch 17:15", "Neben ihm war Johanan, der Oberste, und mit ihm waren zweihundertachtzigtausend;" )
    , ( "Act 11:2", "Und da Petrus hinaufkam gen Jerusalem, zankten mit ihm, die aus den Juden waren," )
    , ( "Gen 32:2", "Jakob aber zog seinen Weg; und es begegneten ihm die Engel Gottes." )
    , ( "Tit 2:15", "Solches rede und ermahne und strafe mit gutem Ernst. Lass dich niemand verachten." )
    , ( "Ecc 6:11", "Denn es ist des eitlen Dinges zuviel; was hat ein Mensch davon?" )
    , ( "1Ch 24:24", "Die Kinder Usiels waren: Micha. Unter den Kindern Michas war Samir." )
    , ( "Psa 71:12", "Gott, sei nicht ferne von mir; mein Gott, eile, mir zu helfen!" )
    , ( "Job 18:10", "Sein Strick ist gelegt in die Erde, und seine Falle auf seinem Gang." )
    , ( "Act 10:13", "Und es geschah eine Stimme zu ihm: Stehe auf, Petrus, schlachte und iss!" )
    , ( "Jdg 20:7", "Siehe, da seid ihr Kinder Israel alle; schafft euch Rat und tut hierzu!" )
    , ( "Pro 14:13", "Auch beim Lachen kann das Herz trauern, und nach der Freude kommt Leid." )
    , ( "1Ch 7:18", "Und seine Schwester Molecheth gebar Ishod, Abieser und Mahela." )
    , ( "Psa 38:22", "Verlass mich nicht, HERR! Mein Gott, sei nicht ferne von mir!" )
    , ( "Mar 9:27", "Jesus aber ergriff ihn bei der Hand und richtete ihn auf; und er stand auf." )
    , ( "Joh 21:21", "Da Petrus diesen sah, spricht er zu Jesus: Herr, was soll aber dieser?" )
    , ( "Luk 22:29", "Und ich will euch das Reich bescheiden, wie mir's mein Vater beschieden hat," )
    , ( "Exo 39:22", "Und machte den Purpurrock zum Leibrock, gewirkt, ganz von blauem Purpur," )
    , ( "2Co 6:11", "O ihr Korinther! unser Mund hat sich zu euch aufgetan, unser Herz ist weit." )
    , ( "Luk 2:45", "Und da sie ihn nicht fanden, gingen sie wiederum gen Jerusalem und suchten ihn." )
    , ( "Num 3:21", "Dies sind die Geschlechter von Gerson: die Libniter und Simeiter." )
    , ( "Psa 69:35", "Es lobe ihn Himmel, Erde und Meer und alles, was sich darin regt." )
    , ( "Eze 33:17", "Aber dein Volk spricht: Der HERR urteilt nicht recht, so sie doch unrecht haben." )
    , ( "Heb 13:8", "Jesus Christus gestern und heute und derselbe auch in Ewigkeit." )
    , ( "Psa 18:13", "Vom Glanz vor ihm trennten sich die Wolken mit Hagel und Blitzen." )
    , ( "Psa 78:36", "und heuchelten ihm mit ihrem Munde und logen ihm mit ihrer Zunge;" )
    , ( "Heb 9:27", "Und wie den Menschen gesetzt ist, einmal zu sterben, darnach aber das Gericht:" )
    , ( "Psa 38:8", "Denn meine Lenden verdorren ganz, und ist nichts Gesundes an meinem Leibe." )
    , ( "Ezr 10:28", "unter den Kindern Bebai: Johanan, Hananja, Sabbai und Athlai;" )
    , ( "Lev 20:8", "Und haltet meine Satzungen und tut sie; denn ich bin der HERR, der euch heiligt." )
    , ( "Pro 7:8", "der ging auf der Gasse an einer Ecke und trat daher auf dem Wege bei ihrem Hause," )
    , ( "Gen 27:35", "Er aber sprach: Dein Bruder ist gekommen mit List und hat deinen Segen hinweg." )
    , ( "Lev 11:30", "der Igel, der Molch, die Eidechse, die Blindschleiche und der Maulwurf;" )
    , ( "Luk 1:23", "Und es begab sich, da die Zeit seines Amts aus war, ging er heim in sein Haus." )
    , ( "Neh 11:18", "Alle Leviten in der heiligen Stadt waren zweihundert und vierundachtzig." )
    , ( "Gal 3:20", "Ein Mittler aber ist nicht eines Mittler; Gott aber ist einer." )
    , ( "Psa 78:48", "da er ihr Vieh schlug mit Hagel und ihre Herden mit Wetterstrahlen;" )
    , ( "Hab 3:12", "Du zertratest das Land im Zorn und zerdroschest die Heiden im Grimm." )
    , ( "Joh 6:6", "(Das sagte er aber, ihn zu versuchen; denn er wusste wohl, was er tun wollte.)" )
    , ( "Job 32:21", "Ich will niemands Person ansehen und will keinem Menschen schmeicheln." )
    , ( "Job 15:6", "Dein Mund verdammt dich, und nicht ich; deine Lippen zeugen gegen dich." )
    , ( "Psa 71:5", "Denn du bist meine Zuversicht, HERR, meine Hoffnung von meiner Jugend an." )
    , ( "Joh 18:7", "Da fragte er sie abermals: Wen suchet ihr? Sie sprachen: Jesum von Nazareth." )
    , ( "2Ki 24:11", "Und Nebukadnezar kam zur Stadt, da seine Knechte sie belagerten." )
    , ( "Isa 56:9", "Alle Tiere auf dem Felde, kommet, und fresset, ja alle Tiere im Walde!" )
    , ( "Gen 43:20", "und sprachen: Mein Herr, wir sind das erstemal herabgezogen Speise zu kaufen," )
    , ( "Joh 6:36", "Aber ich habe es euch gesagt, dass ihr mich gesehen habt, und glaubet doch nicht." )
    , ( "Psa 81:3", "Hebet an mit Psalmen und gebet her die Pauken, liebliche Harfen mit Psaltern!" )
    , ( "1Ki 18:17", "Und da Ahab Elia sah, sprach Ahab zu ihm: Bist du, der Israel verwirrt?" )
    , ( "Joh 17:18", "Gleichwie du mich gesandt hast in die Welt, so sende ich sie auch in die Welt." )
    , ( "Gal 4:16", "Bin ich denn damit euer Feind geworden, dass ich euch die Wahrheit vorhalte?" )
    , ( "Mat 13:7", "Etliches fiel unter die Dornen; und die Dornen wuchsen auf und erstickten's." )
    , ( "Isa 49:11", "Ich will alle meine Berge zum Wege machen, und meine Pfade sollen gebahnt sein." )
    , ( "Lam 3:37", "Wer darf denn sagen, dass solches geschehe ohne des HERRn Befehl" )
    , ( "Gen 35:13", "Also fuhr Gott auf von ihm von dem Ort, da er mit ihm geredet hatte." )
    , ( "Mat 17:8", "Da sie aber ihre Augen aufhoben, sahen sie niemand denn Jesum allein." )
    , ( "Lam 3:4", "Er hat mir Fleisch und Haut alt gemacht und mein Gebein zerschlagen." )
    , ( "Jer 41:4", "Des andern Tages, nachdem Gedalja erschlagen war und es noch niemand wusste," )
    , ( "Psa 109:26", "Stehe mir bei, HERR, mein Gott! hilf mir nach deiner Gnade," )
    , ( "Rom 11:35", "Oder wer hat ihm etwas zuvor gegeben, dass ihm werde wiedervergolten?" )
    , ( "Num 1:54", "Und die Kinder Israel taten alles, wie der HERR dem Mose geboten hatte." )
    , ( "Job 41:20", "Kein Pfeil wird ihn verjagen; die Schleudersteine sind ihm wie Stoppeln." )
    , ( "Joh 12:41", "Solches sagte Jesaja, da er seine Herrlichkeit sah und redete von ihm." )
    , ( "Psa 94:1", "HERR, Gott, des die Rache ist, Gott, des die Rache ist, erscheine!" )
    , ( "Mat 24:35", "Himmel und Erde werden vergehen; aber meine Worte werden nicht vergehen." )
    , ( "Num 33:44", "Von Oboth zogen sie aus und lagerten sich in Ije-Abarim, in der Moabiter Gebiet." )
    , ( "Pro 16:8", "Es ist besser ein wenig mit Gerechtigkeit denn viel Einkommen mit Unrecht." )
    , ( "1Sa 20:4", "Jonathan sprach zu David: Ich will an dir tun, was dein Herz begehrt." )
    , ( "2Sa 5:10", "Und David nahm immer mehr zu, und der HERR, der Gott Zebaoth, war mit ihm." )
    , ( "Jdg 16:22", "Aber das Haar seines Hauptes fing an, wieder zu wachsen, wo es geschoren war." )
    , ( "Amo 5:20", "Denn des HERRn Tag wird ja finster und nicht licht sein, dunkel und nicht hell." )
    , ( "Psa 37:15", "Aber ihr Schwert wird in ihr Herz gehen, und ihr Bogen wird zerbrechen." )
    , ( "Pro 22:20", "Habe ich dir's nicht mannigfaltig vorgeschrieben mit Rat und Lehren," )
    , ( "Exo 21:23", "Kommt ihr aber ein Schade daraus, so soll er lassen Seele um Seele," )
    , ( "2Ti 3:17", "dass ein Mensch Gottes sei vollkommen, zu allem guten Werk geschickt." )
    , ( "Psa 44:19", "Unser Herz ist nicht abgefallen noch unser Gang gewichen von deinem Weg," )
    , ( "Joh 1:20", "Und er bekannte und leugnete nicht; und er bekannte: Ich bin nicht Christus." )
    , ( "1Jo 2:3", "Und an dem merken wir, dass wir ihn kennen, so wir seine Gebote halten." )
    , ( "Jos 10:15", "Josua aber zog wieder ins Lager gen Gilgal und das ganze Israel mit ihm." )
    , ( "Jos 8:30", "Da baute Josua dem HERRn, dem Gott Israels, einen Altar auf dem Berge Ebal" )
    , ( "Jon 1:1", "Es geschah das Wort des HERRn zu Jona, dem Sohn Amitthais, und sprach:" )
    , ( "Mat 24:42", "Darum wachet, denn ihr wisset nicht, welche Stunde euer Herr kommen wird." )
    , ( "1Co 16:4", "So es aber wert ist, dass ich auch hinreise, sollen sie mit mir reisen." )
    , ( "Psa 81:12", "Aber mein Volk gehorcht nicht meiner Stimme, und Israel will mich nicht." )
    , ( "Psa 109:22", "Denn ich bin arm und elend; mein Herz ist zerschlagen in mir." )
    , ( "Psa 83:10", "Tue ihnen, wie den Midianitern, wie Sisera, wie Jabin am Bach Kison," )
    , ( "Pro 17:17", "Ein Freund liebt allezeit, und als ein Bruder wird er in Not erfunden." )
    , ( "Psa 21:5", "Er bittet Leben von dir; so gibst du ihm langes Leben immer und ewiglich." )
    , ( "Psa 105:39", "Er breitete eine Wolke aus zur Decke und ein Feuer, des Nachts zu leuchten." )
    , ( "Job 20:14", "so wird seine Speise inwendig im Leibe sich verwandeln in Otterngalle." )
    , ( "Gen 8:14", "Also ward die Erde ganz trocken am siebenundzwanzigsten Tage des zweiten Monats." )
    , ( "Psa 119:146", "Ich rufe zu dir; hilf mir, dass ich deine Zeugnisse halte." )
    , ( "Zec 9:6", "Zu Asdod werden Fremde wohnen; und ich will der Philister Pracht ausrotten." )
    , ( "Psa 1:4", "Aber so sind die Gottlosen nicht, sondern wie Spreu, die der Wind verstreut." )
    , ( "Job 22:9", "die Witwen hast du leer lassen gehen und die Arme der Waisen zerbrochen." )
    , ( "Jud 1:19", "Diese sind es, die da Trennungen machen, Fleischliche, die da keinen Geist haben." )
    , ( "Pro 24:32", "Da ich das sah, nahm ich's zu Herzen und schaute und lernte daran." )
    , ( "2Sa 14:23", "Also macht sich Joab auf und zog gen Gessur und brachte Absalom gen Jerusalem." )
    , ( "1Ch 3:13", "des Sohn war Ahas; des Sohn war Hiskia; des Sohn war Manasse;" )
    , ( "1Ch 6:12", "des Sohn war Eliab; des Sohn war Jeroham; des Sohn war Elkana." )
    , ( "3Jo 1:7", "Denn um seines Namens willen sind sie ausgezogen und nehmen von den Heiden nichts." )
    , ( "Jos 10:43", "Und Josua zog wieder ins Lager gen Gilgal mit dem ganzen Israel." )
    , ( "Tit 3:4", "Da aber erschien die Freundlichkeit und Leutseligkeit Gottes, unsres Heilandes," )
    , ( "Joh 3:33", "Wer es aber annimmt, der besiegelt's, dass Gott wahrhaftig sei." )
    , ( "1Ch 24:18", "das dreiundzwanzigste auf Delaja, das vierundzwanzigste auf Maasja." )
    ]


benignTextsGerman : List ( String, String )
benignTextsGerman =
    [ ( "", "Das Netz trainiert noch. =)" )
    ]
